README.md

Shame that project and repo are hard coded such that it needs updating when forking this repository.

Add badge for Travis build status to README

---

packages/xs/xapi-stdext.2.1.0/opam

xapi-stdext: fix uninstall script in the opam file

---

travis.sh

Add testing for the often forgotten uninstall scripts

travis: test XS packages uninstall scripts

---

packages/xs/netlink.0.2.1/opam
packages/xs/xapi-netdev.1.0.0/opam

netlink, xapi-netdev: fix uninstall script

---

README.md

This fixes the broken layout introduced in the previous commit and adds a bit of polish.

Update README (2)

---

packages/xs-extra/vncproxy.master/descr
packages/xs-extra/vncproxy.master/opam
packages/xs-extra/vncproxy.master/url
travis.sh

Add vncproxy to xs-extra

---

packages/upstream/shared-block-ring.2.3.0/opam

Add constraint to shared-block-ring

---

packages/upstream/xenstore.1.3.0/opam
packages/xs-extra/vncproxy.master/opam
packages/xs-extra/wsproxy.master/descr
packages/xs-extra/wsproxy.master/opam
packages/xs-extra/wsproxy.master/url
travis.sh

plus update xenstore opam file

Add wsproxy to xs-extra

---

packages/upstream/shared-block-ring.2.3.0/opam

Add constraint to shared-block-ring package

---

README.md
travis.sh

Update README after introducing upstream-extra

---

packages/upstream-extra/qcheck.0.5.3.1/descr
packages/upstream-extra/qcheck.0.5.3.1/opam
packages/upstream-extra/qcheck.0.5.3.1/url
packages/upstream-extra/qtest.2.5/descr
packages/upstream-extra/qtest.2.5/opam
packages/upstream-extra/qtest.2.5/url

upstream-extra: introduce qcheck and qtest to solve travis issues

---

travis.sh

This should make adding packages in xs/ easier as now we will try to
compile them on Travis by default.

For Travis, move from whitelist to blacklist for packages in xs

---

packages/xs-extra/rrd2csv.master/descr
packages/xs-extra/rrd2csv.master/opam
packages/xs-extra/rrd2csv.master/url

This is not whitelisted in the tests. It requires xapi dependencies.

rrd2csv: introduce to xs-extra

---

packages/xs-extra/xapi-forkexecd.master/opam

fokexecd: fix uninstall step in opamfile

---

packages/xs-extra/xapi-netdev.master/opam
packages/xs-extra/xapi-tapctl.master/opam

Fix uninstall of netdev and tapctl

---

packages/xs-extra/xapi-rrdd.master/opam
packages/xs-extra/xapi-xenopsd.master/opam

update xapi-rrdd and xapi-xenopsd opam files

---

packages/xs-extra/xapi-xenopsd.master/opam

xenopsd: update opam file

---

.gitignore
README.md

09d103e 2017-04-02 Update README: Travis builds and role of in.. ..ian Lindig
15d4f83 2017-04-02 Update .gitignore                             ..ian Lindig
This PR updates README and .gitignore to explain that Travis build success is determined by a subset of packages.

Update README, .gitignore

---

packages/xs-extra/xapi-networkd.master/descr
packages/xs-extra/xapi-networkd.master/opam
packages/xs-extra/xapi-networkd.master/url
packages/xs/netlink.0.2.1/opam

update netlink opam file and introduce xapi-networkd

---

packages/xs-extra/xapi-tapctl.master/opam

the opam file with the one in its source repo.

tapctl: add missing dependencies and sync

---

README.md

We should mention which compiler version works with the repository, to make the users' lives easier.

Mention supported OCaml version

---

packages/xs-extra/xapi-nbd.master/descr
packages/xs-extra/xapi-nbd.master/opam
packages/xs-extra/xapi-nbd.master/url

Add xapi-nbd package

---

packages/xs-extra/xapi-storage-cli.master/opam

Update opam file of xapi-storage-cli

---

packages/upstream/mustache.3.0.0/descr
packages/upstream/mustache.3.0.0/opam
packages/upstream/mustache.3.0.0/url

CA-245333: Added mustache package (SDK build dependency).

---

packages/xs/xapi-rrd.1.0.0/opam
packages/xs/xapi-rrd.1.0.0/url

Merge with the one in its repo, change formatting, update maintainers
and tags to xapi-project.

Update opam file of xapi-rrd

---

packages/xs-extra/xapi.master/opam

As per request at https://github.com/xapi-project/xen-api/pull/3038

CA-245333: Added mustache package to the xapi dependencies.

---

packages/xs-extra/vhd-tool.master/descr
packages/xs-extra/vhd-tool.master/opam
packages/xs-extra/vhd-tool.master/url

Fixes https://github.com/xapi-project/xs-opam/issues/84.

Add vhd-tool to xs-extra

---

packages/xs-extra/message-switch.master/opam
packages/xs-extra/xapi-idl.master/opam
packages/xs-extra/xapi-nbd.master/opam
packages/xs-extra/xapi-squeezed.master/opam
packages/xs-extra/xapi-storage-ffs.master/opam
packages/xs-extra/xapi-xenopsd.master/opam
packages/xs/nbd.2.1.3/opam
packages/xs/xen-api-client.0.9.14/opam
packages/xs/xenctrl.dummy/opam

And fix some outdated/out-of-sync packages.

Add cohttp<0.22.0, lwt<3.0.0, mirage<3.0.0 bounds to all our packages

---

packages/xs-extra/message-switch.master/opam

Remove unused dependencies, add version constraints.

Update the opam file of message-switch

---

packages/xs-extra/message-switch.master/opam
packages/xs-extra/vhd-tool.master/opam
packages/xs-extra/xapi-forkexecd.master/opam
packages/xs-extra/xapi-idl.master/opam
packages/xs-extra/xapi-tapctl.master/opam
packages/xs/xapi-backtrace.0.4/opam
packages/xs/xapi-inventory.1.0.2/opam
packages/xs/xapi-rrd.1.0.0/opam
packages/xs/xapi-stdext.2.1.0/opam
packages/xs/xen-api-client.0.9.14/opam

Sync opam files with main OPAM repo

---

packages/xs/xen-api-client.0.9.14/opam

xen-api-client: add build-test

---

packages/xs/qmp.0.9.4/opam

Signed-off-by: Liang Dai <liang.dai1@citrix.com>

Add oasis dependency to ocaml-qmp

---

packages/xs-extra/xapi.master/opam

xapi: fix uninstallation

---

packages/xs-extra/xapi-libs-transitional.master/opam

After https://github.com/xapi-project/xen-api-libs-transitional/pull/33

xapi-libs-transitional: sync opam file with source repo

---

packages/xs-extra/rrd2csv.master/opam
packages/xs-extra/xapi-nbd.master/opam

Update rrd2csv and xapi-nbd opam files

---

packages/xs-extra/xenctrl.master/opam

xs-extra/xenctrl: sync opam file with source repo

---

packages/upstream/jbuilder.1.0+beta10/descr
packages/upstream/jbuilder.1.0+beta10/opam
packages/upstream/jbuilder.1.0+beta10/url

Introduce jbuilder to 1.0.0+beta10

---

packages/xs-extra/xen-api-sdk.master/opam

Moved the SDK build from oasis to jbuilder.

---

packages/upstream/angstrom.0.4.0/descr
packages/upstream/angstrom.0.4.0/opam
packages/upstream/angstrom.0.4.0/url

Add an older angstrom version

---

.travis.yml
README.md
travis.sh

This also reorganises the build targets

Use docker to slightly speed up Travis build

---

packages/xs-extra/vncproxy.master/opam

Ported vncproxy to build with jbuilder.

---

packages/xs-extra/message-switch.master/opam

Sync opam file of message-switch with source repo

---

packages/upstream/lwt.2.7.1/opam

lwt: add missing cppo_ocamlbuild dependency

---

packages/xs-extra/vhd-tool.master/opam

This one depends on https://github.com/xapi-project/vhd-tool/pull/44

Ported build from oasis to jbuilder.

---

packages/xs-extra/xapi-nbd.master/opam

xapi-nbd: sync opam file with source repo

---

packages/upstream/asn1-combinators.0.1.3/descr
packages/upstream/asn1-combinators.0.1.3/opam
packages/upstream/asn1-combinators.0.1.3/url
packages/upstream/conf-gmp.1/descr
packages/upstream/conf-gmp.1/files/test.c
packages/upstream/conf-gmp.1/opam
packages/upstream/conf-perl.1/descr
packages/upstream/conf-perl.1/opam
packages/upstream/mirage-no-xen.1/descr
packages/upstream/mirage-no-xen.1/opam
packages/upstream/nocrypto.0.5.3/descr
packages/upstream/nocrypto.0.5.3/opam
packages/upstream/nocrypto.0.5.3/url
packages/upstream/x509.0.5.3/descr
packages/upstream/x509.0.5.3/opam
packages/upstream/x509.0.5.3/url
packages/upstream/zarith.1.7/descr
packages/upstream/zarith.1.7/opam
packages/upstream/zarith.1.7/url

For reading the subjects from x509 TLS certificates, to return
in the subject fields of the Vdi.get_nbd_info return value.

CA-269137: add x509 and dependencies

---

packages/xs-extra/xapi.master/opam

Add new x509, xapi-tapctl, and yojson dependencies.

xapi: sync opam file with source repo

---

packages/xs-extra/xapi-datamodel.master/opam

See https://github.com/xapi-project/xen-api/pull/3343

Add mustache dependency

---

.travis.yml

Signed-off-by: Iglói Gábor <gaborigloi@gmail.com>

.travis.yml: push xs-opam image to Docker Hub

---

packages/xs-extra/xapi-xenopsd-simulator.master/descr
packages/xs-extra/xapi-xenopsd-simulator.master/opam
packages/xs-extra/xapi-xenopsd-simulator.master/url
packages/xs-extra/xapi-xenopsd-xc.master/descr
packages/xs-extra/xapi-xenopsd-xc.master/opam
packages/xs-extra/xapi-xenopsd-xc.master/url
packages/xs-extra/xapi-xenopsd-xenlight.master/descr
packages/xs-extra/xapi-xenopsd-xenlight.master/opam
packages/xs-extra/xapi-xenopsd-xenlight.master/url
packages/xs-extra/xapi-xenopsd.master/descr

This depends on https://github.com/xapi-project/xenopsd/pull/421

Updated packages after porting xenopsd from oasis to jbuilder.

---

README.md

Document docker images pushed to docker hub

---

.gitignore
.travis.yml
README.md
build-docker.sh

This script allows one to run our Travis build locally.

Add script for building the repo locally in a container

---

build-docker.sh

build-docker.sh: fix here document

---

packages/xs-extra/rrd2csv.master/opam

rrd2csv: fix dependency (xapi -> xapi-client)

---

packages/xs-extra/xapi-networkd.master/opam

xapi-networkd: update opam file after port to jbuilder

---

packages/xs-extra/xapi-xenops-utils.master/descr
packages/xs-extra/xapi-xenops-utils.master/opam
packages/xs-extra/xapi-xenops-utils.master/url
packages/xs-extra/xenops.master/descr
packages/xs-extra/xenops.master/opam
packages/xs-extra/xenops.master/url

and introduce the compatibility package xenops and xapi-xenops-utils

xapi-xenops: bring up-to-date with new jbuildered xenops

---

packages/xs-extra/rrd-transport.master/descr
packages/xs-extra/rrd-transport.master/opam
packages/xs-extra/rrd-transport.master/url
packages/xs-extra/rrdd-plugin.master/descr
packages/xs-extra/rrdd-plugin.master/opam
packages/xs-extra/rrdd-plugin.master/url
packages/xs-extra/xapi-rrd-transport-utils.master/descr
packages/xs-extra/xapi-rrd-transport-utils.master/opam
packages/xs-extra/xapi-rrd-transport-utils.master/url
packages/xs-extra/xapi-rrdd-plugin.master/opam
packages/xs-extra/xenctrl.master/files/0001-Fix-lwt-dependency.patch
packages/xs-extra/xenctrl.master/opam
packages/xs/xenctrl.dummy/opam

xenctrl: fix opam dependencies

---

packages/xs-extra/xapi-rrdd.master/opam

xapi-rrdd: update opam file after port to jbuilder

---

packages/xs-extra/forkexec.master/descr
packages/xs-extra/forkexec.master/opam
packages/xs-extra/forkexec.master/url

forkexec, xapi-forkexecd: update opam files after port to jbuilder

---

packages/xs-extra/xapi-netdev.master/opam
packages/xs-extra/xapi-plugin.master/opam
packages/xs-extra/xapi-storage-cli.master/opam
packages/xs-extra/xapi-tapctl.master/opam

This PR depends on:
https://github.com/xapi-project/ocaml-xapi-plugin/pull/1
https://github.com/xapi-project/netdev/pull/10
https://github.com/xapi-project/sm-cli/pull/24
https://github.com/xapi-project/tapctl/pull/11

CP-26401, CP-26402, CP-26404, CP-26405: Ported build from oasis to jbuilder.

---

packages/xs-extra/xapi-datamodel.master/files/0001-datamodel-setup-the-ulimit-for-the-opam-build.patch
packages/xs-extra/xapi-datamodel.master/opam
travis.sh

This is the most reasonable way I have found to fix the problem.

xapi-datamodel: compile using ulimit to avoid stack overflow

---

packages/xs-extra/xapi.master/opam

xapi.master: add alcotest dependency

---

README.md
packages/upstream-extra/caml2html.1.4.4/descr
packages/upstream-extra/caml2html.1.4.4/files/caml2html.install
packages/upstream-extra/caml2html.1.4.4/opam
packages/upstream-extra/caml2html.1.4.4/url
packages/upstream-extra/camlmix.1.3.0/descr
packages/upstream-extra/camlmix.1.3.0/files/camlmix.install
packages/upstream-extra/camlmix.1.3.0/opam
packages/upstream-extra/camlmix.1.3.0/url
packages/xs-extra/xapi-storage.master/opam

https://github.com/xapi-project/xapi-storage/pull/69

CP-26711: Ported xapi-storage to jbuilder; added library caml2html.

---

travis.sh

fix debian test

---

packages/upstream/shared-block-ring.2.4.0+1/opam

shared-block-ring: add lower bound on lwt

---

packages/upstream/cstruct-unix.3.2.1/descr
packages/upstream/cstruct-unix.3.2.1/opam
packages/upstream/cstruct-unix.3.2.1/url

Add cstruct-unix

---

packages/xs-extra/xapi-xenopsd-xc.master/opam
packages/xs-extra/xapi-xenopsd.master/opam
packages/xs-extra/xcp.master/opam
packages/xs/nbd.4.0.0+beta1/opam

xcp, xapi-xenopsd, xapi-xenopsd-xc: sync opam files

---

.travis.yml

https://travis-ci.org/xapi-project/xs-opam/builds/391797347

-safe-string build is green now: lets keep it that way

---

packages/xs/xenctrl.dummy/opam

Signed-off-by: Yang Qian <yang.qian@citrix.com>

CP-28951: Add package xeneventchn to opam

---

packages/xs-extra/message-switch-async.master/opam
packages/xs-extra/message-switch-cli.master/opam
packages/xs-extra/message-switch-core.master/opam
packages/xs-extra/message-switch-lwt.master/opam
packages/xs-extra/message-switch-unix.master/opam
packages/xs-extra/message-switch.master/opam
packages/xs-extra/rrd-transport.master/opam
packages/xs-extra/xapi-forkexecd.master/opam
packages/xs-extra/xapi-idl.master/opam
packages/xs-extra/xapi-rrd-transport-utils.master/opam
packages/xs-extra/xapi-rrd-transport.master/opam
packages/xs-extra/xapi-xenops-utils.master/opam
packages/xs-extra/xapi-xenops.master/opam
packages/xs-extra/xcp.master/opam
packages/xs-extra/xenops.master/opam
tools/opam-sources.sh

This updates opam files with versions that are in the corresponding code
repositories. In a few cases this is a regression where the maintainer
is updated but it makes the repositories the source of truth, as it
should be.

Sync opam files with code repos

---

packages/xs-extra/vncproxy.master/opam

Goes with https://github.com/xapi-project/vncproxy/pull/13
Please feel free to merge both if approved.

Port to dune.

---

packages/upstream/ppx_deriving_rpc.6.0.0/opam
packages/upstream/rpc.6.0.0/opam
packages/upstream/rpclib-async.6.0.0/opam
packages/upstream/rpclib-lwt.6.0.0/opam
packages/upstream/rpclib.6.0.0/opam

New release of rpclib

---

packages/xs/crc.2.0.0/opam

Goes with https://github.com/xapi-project/ocaml-crc/pull/28

Completed port to dune.

---

packages/upstream/oasis.0.4.11/opam
packages/upstream/ocamlmod.0.0.9/opam
packages/upstream/ounit.2.0.8/opam

The old URLs do not work for me any more.

Sync oasis, ocamlmod, ounit opam files with upstream to use new URLs

---

packages/xs-extra/xapi-idl.master/opam

Added missing build instruction.

---

packages/xs-extra/forkexec.master/opam
packages/xs-extra/rrd-transport.master/opam
packages/xs-extra/rrdd-plugin.master/opam
packages/xs-extra/xapi-database.master/opam
packages/xs-extra/xapi-forkexecd.master/opam
packages/xs-extra/xapi-rrd-transport-utils.master/opam
packages/xs-extra/xapi-rrd-transport.master/opam
packages/xs-extra/xapi-storage-cli.master/opam
packages/xs-extra/xapi-storage-script.master/opam
packages/xs-extra/xapi-tapctl.master/opam
packages/xs-extra/xapi-types.master/opam
packages/xs-extra/xapi-xenops-utils.master/opam
packages/xs-extra/xapi-xenopsd-xc.master/opam

This takes changes in opam files in code repositories and brings them into this repository.

Update some opam files from code repos

---

packages/xs/ezxenstore.0.3.1/opam

New release ezxenstore.0.3.1

---

packages/xs-extra/vncproxy.master/opam
packages/xs-extra/wsproxy.master/opam
packages/xs-extra/xapi-cli-protocol.master/opam
packages/xs-extra/xapi-client.master/opam
packages/xs-extra/xapi-consts.master/opam
packages/xs-extra/xapi-database.master/opam
packages/xs-extra/xapi-datamodel.master/opam
packages/xs-extra/xapi-idl.master/opam
packages/xs-extra/xapi-nbd.master/opam
packages/xs-extra/xapi-plugin.master/opam
packages/xs-extra/xapi-storage.master/opam
packages/xs-extra/xapi-types.master/opam
packages/xs-extra/xapi-xenopsd-xc.master/opam
packages/xs-extra/xapi-xenopsd.master/opam
packages/xs-extra/xapi.master/opam
packages/xs-extra/xe.master/opam
packages/xs-extra/xen-api-client-async.master/opam
packages/xs-extra/xen-api-client-lwt.master/opam
packages/xs-extra/xen-api-client.master/opam
packages/xs-extra/xen-api-sdk.master/opam
packages/xs-extra/xenops.master/opam

Changes are mostly updating to dune and dependencies that got added, renamed or removed.

CP-30756: Update xs-extra packages

---

packages/xs/qmp.0.17.0/opam

Tagged latest change to qmp that includes the optional PCI device address change.

CP-30136: qmp.0.17.0

---

packages/xs-extra/rrd-transport.master/opam

rrd-transport: add ezjsonm dependency

---

packages/xs/xapi-rrd.1.5.0/opam

xapi-rrd: update to 1.5.0 for CA-315952 XSI-335

---

packages/xs/stdext.4.7.0/opam
packages/xs/xapi-stdext-bigbuffer.4.7.0/opam
packages/xs/xapi-stdext-date.4.7.0/opam
packages/xs/xapi-stdext-deprecated.4.7.0/opam
packages/xs/xapi-stdext-encodings.4.7.0/opam
packages/xs/xapi-stdext-monadic.4.7.0/opam
packages/xs/xapi-stdext-pervasives.4.7.0/opam
packages/xs/xapi-stdext-range.4.7.0/opam
packages/xs/xapi-stdext-std.4.7.0/opam
packages/xs/xapi-stdext-threads.4.7.0/opam
packages/xs/xapi-stdext-unix.4.7.0/opam
packages/xs/xapi-stdext-zerocheck.4.7.0/opam

This is part of the update of base64. 

Update stdext to 4.7.0

---

packages/xs/xapi-test-utils.1.3.0/opam

Signed-off-by: Rob Hoes <rob.hoes@citrix.com>

Fix xapi-test-utils opam dependencies

---

packages/xs-extra/xapi.master/opam

Signed-off-by: Rob Hoes <rob.hoes@citrix.com>

xapi: remove unused netdev dependency

---

.travis.yml
packages/ocaml/ocaml-base-compiler.4.08.1/opam
packages/ocaml/ocaml-system.4.08.1/files/gen_ocaml_config.ml.in
packages/ocaml/ocaml-system.4.08.1/opam
packages/ocaml/ocaml.4.08.1/opam
packages/upstream/ppx_tools.5.3+4.08.0/opam
tools/travis.sh

Thanks to @psafont update of opam packages there is now very little preventing us from starting to test 4.08 (just ppx_tools which requires a different version).

Add 4.08.1 for testing

---

packages/xs-extra-dummy/xs-toolstack.master/opam
packages/xs-extra/xenops-cli.master/opam
tools/generate-opam-sources.sh

Add xenops-cli

---

packages/upstream-extra/afl-persistent.1.3/opam
packages/upstream-extra/crowbar.0.1/opam
packages/upstream-extra/ocp-indent.1.8.1/opam

Also updated ocp-indent checksums, somehow they have changed and broke installation.

Add crowbar

---

packages/xs/xapi-rrd.1.8.0/opam

Includes a fix for a bug introduced in 1.7.0

xs: bump xcp-rrd

---

packages/upstream/x509.0.8.1/opam

CP-32055: update x509 to 0.8.1

---

README.md

Signed-off-by: lippirk <ben.anson@citrix.com>

maintenance: update travis build instructions

---

packages/xs-extra/rrdd-plugins.master/opam
packages/xs-extra/xen-api-client-lwt.master/opam
tools/generate-opam-sources.sh

moved rrdd-plugins out of the dummy directory as it's a actual package

maintenance: update metadata for xs-extra packages

---

tools/Dockerfile

Signed-off-by: lippirk <ben.anson@citrix.com>

maintenance: upgrade Dockerfile to ocaml 4.08

---

tools/travis.sh
tools/xs-opam-ci.env

This should hopefully show us what the build failure is

Print more log lines on build failures

---

packages/xs/dlm.0.3.1/opam

CP-33380: Fix installation of dlm with dune 2

---

packages/xs/nbd-lwt-unix.4.0.1/opam
packages/xs/nbd-tool.4.0.1/opam
packages/xs/nbd.4.0.1/opam

checksums, and one url were incorrect

Fix nbd checksums

---

Makefile
packages/xs-extra/xen-api-client.master/opam

fixup! CP-32669: update xs-extra opam files

---

packages/xs/stdext.4.8.0/opam
packages/xs/xapi-stdext-bigbuffer.4.8.0/opam
packages/xs/xapi-stdext-date.4.8.0/opam
packages/xs/xapi-stdext-deprecated.4.8.0/opam
packages/xs/xapi-stdext-encodings.4.8.0/opam
packages/xs/xapi-stdext-monadic.4.8.0/opam
packages/xs/xapi-stdext-pervasives.4.8.0/opam
packages/xs/xapi-stdext-range.4.8.0/opam
packages/xs/xapi-stdext-std.4.8.0/opam
packages/xs/xapi-stdext-threads.4.8.0/opam
packages/xs/xapi-stdext-unix.4.8.0/opam
packages/xs/xapi-stdext-zerocheck.4.8.0/opam

Signed-off-by: lippirk <ben.anson@citrix.com>

CA-333908 bump stdext with datetime changes

---

packages/xs/stdext.4.11.0/opam
packages/xs/xapi-stdext-bigbuffer.4.11.0/opam
packages/xs/xapi-stdext-date.4.11.0/opam
packages/xs/xapi-stdext-deprecated.4.11.0/opam
packages/xs/xapi-stdext-encodings.4.11.0/opam
packages/xs/xapi-stdext-monadic.4.11.0/opam
packages/xs/xapi-stdext-pervasives.4.11.0/opam
packages/xs/xapi-stdext-range.4.11.0/opam
packages/xs/xapi-stdext-std.4.11.0/opam
packages/xs/xapi-stdext-threads.4.11.0/opam
packages/xs/xapi-stdext-unix.4.11.0/opam
packages/xs/xapi-stdext-zerocheck.4.11.0/opam

Removed Legacy variant in iso8601 type

CA-338243 bump stdext (again)

---

packages/xs-extra/varstored-guard.master/opam
packages/xs-extra/xapi-consts.master/opam
packages/xs-extra/xapi-database.master/opam
packages/xs-extra/xapi.master/opam

Add xapi-inventory as to xapi-consts.master 
and updated: varstored-guard.master/opam, xapi-consts.master/opam, xapi-database.master/opam, xapi.master/opam, xenctrl.master/opam
Signed-off-by: Gheorghe Burac <gheorghe.burac@citrix.com>

Sync opam dependencies for xs-extra/ from source repos

---

packages/xs-extra/xe.master/opam

CA-338596: Update xe to use fpath

---

packages/xs-extra/xapi-cli-protocol.master/opam
packages/xs-extra/xapi-client.master/opam
packages/xs-extra/xapi-consts.master/opam
packages/xs-extra/xapi-database.master/opam
packages/xs-extra/xapi-datamodel.master/opam
packages/xs-extra/xapi-types.master/opam
packages/xs-extra/xapi.master/opam
packages/xs-extra/xe.master/opam

sibling of https://github.com/xapi-project/xen-api/pull/4100

CA-334811 set dummy XAPI_VERSION var

---

packages/upstream-extra/depext.transition/opam

Give stockholm the same treatment as master (see #467)

Reintroduce depext.transition for release/stockholm/lcm

---

.github/workflows/main.yml
tools/xs-opam-ci.env

The interface can be seen here: https://github.com/psafont/xs-opam/actions

ci: enable testing through github actions

---

.github/workflows/main.yml

The indentation was incorrect, blocking builds.

github actions: enable builds on pull requests

---

.github/workflows/main.yml
.travis.yml
tools/travis.sh

It never succeeded and there's little chance this can change.

ci: remove job for testing all upstream packages

---

.github/workflows/main.yml

Reference for syntax can be found in https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule

ci: run daily to detect breaking changes in xs-extra

---

packages/xs/nbd-lwt-unix.4.0.2/opam
packages/xs/nbd-tool.4.0.2/opam
packages/xs/nbd.4.0.2/opam

They are now compatible with alcotest 1.1.0

xs: update nbd packages to 4.0.2

---

packages/xs-extra/rrd2csv.master/opam
tools/generate-opam-sources.sh

CP-34439: merge rrd2csv into xen-api

---

README.md

Update README for Docker use case

---

packages/upstream/dune-build-info.2.5.0/opam

For https://github.com/xapi-project/xcp-rrdd/pull/117

add dune-build-info

---

packages/xs-extra/rrd-transport.master/opam
packages/xs-extra/xapi-rrd-transport-utils.master/opam
packages/xs-extra/xapi-rrd-transport.master/opam
packages/xs-extra/xapi-rrdd.master/opam
tools/generate-opam-sources.sh

See https://github.com/xapi-project/xcp-rrdd/pull/117

CP-32672 merge rrd-transport into xcp-rrdd

---

packages/xs/ezxenstore.0.4.1/opam

CA-342986: Keep watches after soft reset of a domain

Update ezxenstore to 0.4.1 for CA-342986

---

.github/workflows/main.yml

Automatically the latest version in the v1 series for setup-ocaml
See https://github.com/avsm/setup-ocaml/releases/tag/v1.1.3

maintenance: update github actions dependency

---

packages/xs-extra/gzip.master/opam
packages/xs-extra/http-svr.master/opam
packages/xs-extra/pciutil.master/opam
packages/xs-extra/safe-resources.master/opam
packages/xs-extra/sexpr.master/opam
packages/xs-extra/stunnel.master/opam
packages/xs-extra/uuid.master/opam
packages/xs-extra/xapi-cli-protocol.master/opam
packages/xs-extra/xapi-client.master/opam
packages/xs-extra/xapi-compression.master/opam
packages/xs-extra/xapi-consts.master/opam
packages/xs-extra/xapi-database.master/opam
packages/xs-extra/xapi-datamodel.master/opam
packages/xs-extra/xapi-libs-transitional.master/opam
packages/xs-extra/xapi-types.master/opam
packages/xs-extra/xapi.master/opam
packages/xs-extra/xe.master/opam
packages/xs-extra/xml-light2.master/opam
packages/xs-extra/zstd.master/opam
tools/xs-opam-ci.env

Both xen-api and xen-api-libs-transitional have changes, track them with this branch.

REQ-403: set up branch 

---

README.md

Travis now has a restrictive limit on number of minutes per month.
No repos in xapi-project have hit it yet, but it's good practice to prepare for it.
The template given should be enough to kickstart github actions any of the repos that are yet to be migrated.

readme: replace ci instructions to use github actions

---

packages/upstream-extra/depext.transition/opam
packages/upstream-extra/opam-depext.1.1.5/opam

Having the outdated package is causing failures in CI, like in https://travis-ci.org/github/xapi-project/nbd/jobs/748916153#L391

CP-34942: update depext package

---

packages/xs/xapi-stdext-date.4.16.0/opam
packages/xs/xapi-stdext-encodings.4.16.0/opam
packages/xs/xapi-stdext-pervasives.4.16.0/opam
packages/xs/xapi-stdext-std.4.16.0/opam
packages/xs/xapi-stdext-threads.4.16.0/opam
packages/xs/xapi-stdext-unix.4.16.0/opam
packages/xs/xapi-stdext-zerocheck.4.16.0/opam

*  XSI-894 date.iso8601.to_float should assume UTC
*  date: allow timezones other than UTC for printing

maintenance: bump stdext

---

Makefile

Like https://github.com/xapi-project/xs-opam/pull/538 but for master

detect failed downloads

---

packages/upstream/xenstore_transport.1.2.0/opam
packages/upstream/xenstore_transport.1.3.0/opam

Update xenstore_transport to 1.2.0

---

packages/upstream/xenstore_transport.1.3.0/opam
packages/xs/cdrom.0.9.4/opam
packages/xs/crc.2.1.0/opam
packages/xs/dlm.0.3.1/opam
packages/xs/ezxenstore.0.4.1/opam
packages/xs/fd-send-recv.2.0.1/opam
packages/xs/netlink.0.3.4/opam
packages/xs/xapi-backtrace.0.7/opam
packages/xs/xapi-inventory.1.2.1/opam
packages/xs/xapi-rrd.1.8.2/opam
packages/xs/xapi-stdext-pervasives.4.16.0/opam
packages/xs/xapi-stdext-std.4.16.0/opam
packages/xs/xapi-stdext-threads.4.16.0/opam
packages/xs/xapi-stdext-unix.4.16.0/opam
tools/default-opam-repo-sync.sh

Also includes the script used to sync, which is pretty barebones.

maintenance: sync packages from default repo

---

packages/xs-extra/xapi.master/opam

xs-extra: update xapi.master to use external pci library

---

packages/upstream/fix.20201120/opam
packages/upstream/menhir.20210310/opam
packages/upstream/menhirLib.20210310/opam
packages/upstream/menhirSdk.20210310/opam

fix: broken links from inria's gitlab

---

.github/workflows/yangtze-lcm.yml

The builds are scheduled daily between master and stockholm builds

maintenance: schedule builds for the yangtze branch

---

packages/xs-extra/message-switch-async.master/opam
packages/xs-extra/message-switch-cli.master/opam
packages/xs-extra/message-switch-core.master/opam
packages/xs-extra/message-switch-lwt.master/opam
packages/xs-extra/message-switch-unix.master/opam
packages/xs-extra/message-switch.master/opam
packages/xs-extra/rrdd-plugins.master/opam
packages/xs-extra/xapi-idl.master/opam
packages/xs-extra/xen-api-client-async.master/opam
packages/xs-extra/xen-api-client-lwt.master/opam
packages/xs-extra/xen-api-client.master/opam
tools/generate-opam-sources.sh

specsavers: merge xapi-idl into message-switch, xen-api-client into xen-api and rrd-plugins into xcp-rrdd

---

packages/xs-extra/rrd-transport.master/opam
packages/xs-extra/rrdd-plugin.master/opam
packages/xs-extra/rrdd-plugins.master/opam
packages/xs-extra/rrddump.master/opam
packages/xs-extra/xapi-rrd-transport-utils.master/opam
packages/xs-extra/xapi-rrd-transport.master/opam
packages/xs-extra/xapi-rrdd-plugin.master/opam
packages/xs-extra/xapi-rrdd.master/opam
tools/generate-opam-sources.sh

xs-opam changes to accompany https://github.com/xapi-project/xen-api/pull/4502

specsavers: xcp-rrdd -> xapi

---

packages/xs-extra/xapi-squeezed.master/opam
tools/generate-opam-sources.sh

Depends on https://github.com/xapi-project/xenopsd/pull/760

CP-37369: merge squeezed into xenopsd

---

packages/xs-extra/forkexec.master/opam
packages/xs-extra/message-switch-async.master/opam
packages/xs-extra/message-switch-cli.master/opam
packages/xs-extra/message-switch-core.master/opam
packages/xs-extra/message-switch-lwt.master/opam
packages/xs-extra/message-switch-unix.master/opam
packages/xs-extra/message-switch.master/opam
packages/xs-extra/xapi-forkexecd.master/opam
packages/xs-extra/xapi-idl.master/opam
packages/xs-extra/xapi-storage-script.master/opam
packages/xs-extra/xapi-storage.master/opam
packages/xs-extra/xen-api-sdk.master/opam
tools/generate-opam-sources.sh

specsavers: move packages to xen-api

---

packages/upstream/unix-errno.0.6.1/opam

Made all libraries public to avoid a dune bug

CP-34942: update unix-errno

---

packages/xs-extra/forkexec.master/opam
packages/xs-extra/gzip.master/opam
packages/xs-extra/http-svr.master/opam
packages/xs-extra/pciutil.master/opam
packages/xs-extra/rrd2csv.master/opam
packages/xs-extra/rrdd-plugins.master/opam
packages/xs-extra/safe-resources.master/opam
packages/xs-extra/sexpr.master/opam
packages/xs-extra/stunnel.master/opam
packages/xs-extra/uuid.master/opam
packages/xs-extra/wsproxy.master/opam
packages/xs-extra/xapi-compression.master/opam
packages/xs-extra/xapi-forkexecd.master/opam
packages/xs-extra/xapi-idl.master/opam
packages/xs-extra/xapi-nbd.master/opam
packages/xs-extra/xapi-rrdd.master/opam
packages/xs-extra/xapi-squeezed.master/opam
packages/xs-extra/xapi-storage-cli.master/opam
packages/xs-extra/xapi-storage-script.master/opam
packages/xs-extra/xapi-storage.master/opam
packages/xs-extra/xapi-types.master/opam
packages/xs-extra/xapi-xenopsd-cli.master/opam
packages/xs-extra/xapi-xenopsd-simulator.master/opam
packages/xs-extra/xapi-xenopsd-xc.master/opam
packages/xs-extra/xapi-xenopsd.master/opam
packages/xs-extra/xen-api-client.master/opam
packages/xs-extra/xen-api-sdk.master/opam
packages/xs-extra/xml-light2.master/opam
packages/xs-extra/zstd.master/opam

CP-34028: refresh xs-extra metadata for uuid changes

---

packages/xs-extra-dummy/xs-toolstack.master/opam
packages/xs-extra/xapi-xenopsd-cli.0.150/opam
tools/generate-opam-sources.sh

xs-extra: change xenops-cli source repo to xenopsd in yangtze release

---

.github/workflows/lcm.yml
packages/xs-extra/rrddump.1.33/opam
packages/xs-extra/xapi-libs-transitional.2.25/opam
packages/xs-extra/xapi-rrdd.1.33/opam

Otherwise tests fail on warning, which is inaccurate

ci: test xapi-libs-transitional using profile=release

---

packages/xs/ezxenstore.0.4.2/opam

xs: update ezxenstore to 0.4.2

---

packages/xs-extra/xapi-schema.master/opam
packages/xs/polly.0.3.0/opam

Signed-off-by: Pau Ruiz Safont <pau.ruizsafont@cloud.com>

xs: update polly to 0.3.0

---

packages/upstream/conf-libcurl.2/opam
packages/upstream/ezcurl.0.2.2-1/files/001-post-non-form-data.patch
packages/upstream/ezcurl.0.2.2-1/opam
packages/upstream/ocaml-protoc.2.3/opam
packages/upstream/ocurl.0.9.1/opam
packages/upstream/opentelemetry-client-ocurl.0.3/opam
packages/upstream/opentelemetry.0.3/opam
packages/upstream/pbrt.2.3/opam
packages/xs-extra/xapi.master/opam

upstream: Add opentelemetry libraries for testing, includes ocurl and ezcurl

---

packages/xs-extra/tracing/opam

Adding opam file for new Tracing library

Adding Tracing Library

---

packages/xs/xapi-rrd.1.8.4/opam

xs: update xapi-rrd to 1.8.4

---

packages/upstream-extra/merlin-lib.4.12-414/opam
packages/upstream-extra/merlin.4.12-414/opam
packages/xs/xapi-rrd.1.11.0/opam

Updates merlin to the newest version as well (which is not packaged)

xs: update xapi-rrd to 1.11.0

---

packages/xs/xapi-stdext-date.4.24.0/opam
packages/xs/xapi-stdext-encodings.4.24.0/opam
packages/xs/xapi-stdext-pervasives.4.24.0/opam
packages/xs/xapi-stdext-std.4.24.0/opam
packages/xs/xapi-stdext-threads.4.24.0/opam
packages/xs/xapi-stdext-unix.4.24.0/opam
packages/xs/xapi-stdext-zerocheck.4.24.0/opam

- unix: really_read now retries reads on EINTR
- std: add Listext.List.find_minimum

xs: update stdext packages to 4.24.0

---

packages/xs-extra/forkexec.master/opam
packages/xs-extra/xapi-idl.master/opam
packages/xs-extra/xapi-tracing-export.master/opam
packages/xs-extra/xapi-xenopsd.master/opam
tools/generate-opam-sources.sh

Adds xapi-tracing-export, following https://github.com/xapi-project/xen-api/pull/5584

xs-extra: update metadata

---

.github/workflows/main.yml
packages/ocaml/ocaml-base-compiler.4.14.2/files/ocaml-base-compiler.install
packages/ocaml/ocaml-base-compiler.4.14.2/opam
packages/ocaml/ocaml-system.4.14.2/files/gen_ocaml_config.ml.in
packages/ocaml/ocaml-system.4.14.2/opam
packages/ocaml/ocaml.4.14.2/opam

Needed to compile xapi with it in xenserver, as part of xs-opam-repo

IH-569, ocaml: add 4.14.2

---

packages/xs-extra/xapi-idl.master/opam
packages/xs-extra/xapi-squeezed.master/opam

Fixes builds for gpumon:
https://github.com/xenserver/gpumon/pull/51
https://github.com/xenserver/gpumon/actions/runs/8987737972/job/24686957953?pr=51

xs-extra: sync metadata

---

packages/upstream/systemd.1.2/opam
packages/xs-extra/xapi-forkexecd.master/opam
packages/xs-extra/xapi-networkd.master/opam
packages/xs-extra/xapi-rrdd.master/opam

Reverts xapi-project/xs-opam#684
Let's give people using feature branches more time to merge from master

Revert "IH-583: Remove systemd package and deps"

---

packages/xapi-debug/xapi-debug.master/opam
packages/xapi/xapi.master/opam

This fixes the CI build in this repository

xapi: add newly required dependencies

---

packages/xapi-debug/xapi-debug.master/opam
packages/xapi-stdext-threads/xapi-stdext-threads.master/opam
packages/xapi-tools/xapi-tools.master/opam

xen-api: update metadata to latest

---

.github/workflows/lcm.yml
packages/xs-extra/xapi-storage.11.19.0_sxm2/opam

The current version is being deprecated

github: use newer version of ubuntu
