Makefile, README.md, xs-opam-repo.in, xs-opam-src.in
* Update README
* Update URLs pointing to repository
* Add current commit hash as comment to auto-generated spec files
=> Move xs-opam repo from github.com/lindig to github.com/xapi-project

LICENSE, utils/sources.rb
The xs-opam repository was moved from github.com/lindig to
github.com/xapi-project recently but we forgot to update the license at
the time.
The sources.rb script computes the URL from where to download a
package's source code. It now accepts a flag such that it can take
mirroring into account.
=> Fix LICENSE to name Citrix, add support for mirroring

.gitattributes
This file is required to make expansion of .gitarchive-info work.
=> Add missing .gitattributes file

travis.sh
This reverts commit b80f82881f5bacf2d40d824658ea8ecaf34c82d9.
xapi-netdev requires systemd, but this is not whitelisted to be
installed in travis, making the install step fail.
=> Revert "travis: add missing library to XS - xapi-netdev"

travis.sh
This simplifies the setup of Opam in the Travis build. The Opam
repository only contains libraries from this repo and never uses
the public remote repository.
Previously the OACML_VERSION variable was not effective because it was
not exported and the script was executed in a sub shell. By exporting
it, it is now effective. Likewise, we use OCAML_INIT to avoid having the
Opam repository being initialised outside the travis.sh script.
=> Simplify and fix Opam setup in Travis

packages/xs-extra/message-switch.master/opam
After https://github.com/xapi-project/message-switch/pull/29, update the `opam` file here to match the one in its source repository, at the HEAD of the master branch.
=> Sync opam file of message-switch

packages/upstream-extra/alcotest.0.7.2/descr, packages/upstream-extra/alcotest.0.7.2/opam, packages/upstream-extra/alcotest.0.7.2/url, travis.sh
And introduce alcotest, necessary to unlock the test pass of the travis builds in some of the other packages repositories.
=> Add upstream-extra to the xs-opam repository

packages/upstream-extra/ocveralls.0.3.4/descr, packages/upstream-extra/ocveralls.0.3.4/findlib, packages/upstream-extra/ocveralls.0.3.4/opam, packages/upstream-extra/ocveralls.0.3.4/url
The version appearing in the URL is 3.3.4, however this is the URL used
in the official opam repository, the hash is the correct one and the
content is the correct one. The original can be seen here: 
https://github.com/ocaml/opam-repository/tree/master/packages/ocveralls/ocveralls.0.3.4
=> upstream-extra: introduce ocveralls for coverage builds

travis.sh
We are now using one shell function to collect the names
of packages in the packages/ hierarchy.
=> Simplify travis.sh

packages/xs-extra/xapi-networkd.master/opam
Passing the correct `MANDIR` should fix the build when we compile the extra packages. :crossed_fingers: 
=> xapi-networkd: fix install/remove

packages/xs-extra/xen-api-sdk.master/descr, packages/xs-extra/xen-api-sdk.master/opam, packages/xs-extra/xen-api-sdk.master/url
This will help us notice when we break the SDK generation code.
I already have a fork of `xen-api-sdk` with this `opam` file, and a working Travis build: https://travis-ci.org/gaborigloi/xen-api-sdk/builds/233636569
=> Add xen-api-sdk to xs-opam

packages/xs-extra/vhd-tool.master/opam, packages/xs-extra/xapi-nbd.master/opam, packages/xs-extra/xapi-rrd-transport.master/opam, packages/xs/crc.1.0.0/opam, packages/xs/nbd.2.1.3/opam, packages/xs/xen-api-client.0.9.14/opam
To fix the build against the upstream opam.
=> Set cstruct < 3.0.0 on all our packages

packages/xs-extra/xapi-rrd-transport.master/opam, packages/xs-extra/xapi-rrdd.master/opam
Version 3.0.0 has been split into two OPAM and ocamlfind packages.
=> Add xen-gnt < 3.0.0 bound to all our packages

packages/xs-extra/wsproxy.master/opam
This will additionally require a change to the specfile when released (more details on wsproxy repo).
Depends on https://github.com/xapi-project/wsproxy/pull/5 
=> wsproxy: port to jbuilder

packages/xs-extra/xapi-xenopsd.master/opam
See https://github.com/xapi-project/xenopsd/pull/350
Thanks to @gaborigloi for the reminder and help with the `remove` rule.
=> update opam after coverage build changes

packages/upstream/cohttp.0.21.1/opam
To fix the build when using xs-opam as an extra remote.
In conduit v1.0.0 the package has been split into multiple packages.
=> cohttp: add conduit < v1.0.0 upper bound

packages/upstream/cohttp.0.21.1/opam
cohttp fails to build with conduit 1.0.0 otherwise.
There seems to have been a typo in the version constraint in our version, 1.0.0 < v1.0.0, so it didn't actually prevent 1.0 from getting installed.
Signed-off-by: Edwin Török <edvin.torok@citrix.com>
=> Update constraints for cohttp from upstream

packages/upstream/oasis.0.4.10/opam
We do not run the tests for oasis, and it would need several packages to be
added to xs-opam to make BASE_REMOTE Travis testing work
(which tries to install the test-only dependencies too).
=> drop oasis test-only dependencies

packages/xs-extra/vncproxy.master/opam, packages/xs-extra/xapi-cli-protocol.master/descr, packages/xs-extra/xapi-cli-protocol.master/opam, packages/xs-extra/xapi-cli-protocol.master/url, packages/xs-extra/xapi-client.master/descr, packages/xs-extra/xapi-client.master/opam, packages/xs-extra/xapi-client.master/url, packages/xs-extra/xapi-consts.master/descr, packages/xs-extra/xapi-consts.master/opam, packages/xs-extra/xapi-consts.master/url, packages/xs-extra/xapi-database.master/descr, packages/xs-extra/xapi-database.master/opam, packages/xs-extra/xapi-database.master/url, packages/xs-extra/xapi-datamodel.master/descr, packages/xs-extra/xapi-datamodel.master/opam, packages/xs-extra/xapi-datamodel.master/url, packages/xs-extra/xapi-idl.master/opam, packages/xs-extra/xapi-types.master/descr, packages/xs-extra/xapi-types.master/opam, packages/xs-extra/xapi-types.master/url, packages/xs-extra/xapi.master/opam, packages/xs-extra/xcp.master/descr, packages/xs-extra/xcp.master/opam, packages/xs-extra/xcp.master/url, packages/xs-extra/xe.master/descr, packages/xs-extra/xe.master/opam, packages/xs-extra/xe.master/url
Depends on https://github.com/xapi-project/xen-api/pull/3274 and https://github.com/xapi-project/vncproxy/pull/12
Also updates:
- vncproxy, to use the new xen-api-client
- xcp-idl, recently ported to jbuilder
=> xapi: introduce new packages after xapi port to jbuild

packages/xs-extra/xen-api-sdk.master/opam
=> xen-api-sdk: depend on xapi-datamodel instead of xapi

.travis.yml
The OCAML_VERSION environment variable needs to be passed to the container for travis.sh.
=> Re-enable install/uninstall checks

packages/upstream/nocrypto.0.5.3/opam
Nocrypto detects CPU features at *build time*, instead of runtime.
If the build machine is newer than the machine you install the binary on then it
would crash with an illegal instruction on startup.
See https://github.com/mirleft/ocaml-nocrypto#illegal-instructions and https://github.com/mirleft/ocaml-nocrypto/issues/73
Since there is no runtime detection the only safe thing to do is to disable the
use of these instructions always.
For version 0.5.3 this is done with `--disable-modernity`, for 0.5.4 it'll be
`NOCRYPTO_ACCELERATE=false` environment variable.
Tested with `opam reinstall -y nocrypto.0.5.3 -v`: without this patch I see `-maes` in the build output, with this patch I do not. (note: you only see `-maes` if `/proc/cpuinfo` has the `aes` flag)
=> Avoid illegal instructions from nocrypto

packages/upstream/x509.0.5.3/opam
Compilation fails with version 0.2.0 of asn1-combinators. The upper bound has already been added to the opam file of x509 in the main OPAM repository, so I've just copied that one.
=> x509: update to add upper bound on asn1-combinators

packages/xs/netlink.0.3.1/opam
Different packages are required on the new Debian stable.
=> netlink: update depexts for Debian 9 Stretch

travis.sh
With jbuilder these are not necessary as the installed files are specifically listed and automatically removed.
Fixes #160
=> Remove install/uninstall checks

packages/upstream/camlp4.4.04+1/opam
camlp4 is also preinstalled for us, but we want both in 
=> camlp4: disable preinstalled check

tools/opam-updates.py
The functionality to detect remote changes is often unreliable with `opam 1.2.2`.
This flag will be used in the updates cron job
=> opam-updates.py: add flag to ignore updates

packages/upstream/nocrypto.0.5.4/opam, packages/upstream/result.1.3/opam
See https://github.com/mirleft/ocaml-nocrypto/issues/136 and the corresponding PR in `opam-repository` https://github.com/ocaml/opam-repository/pull/11032
Also backport a minor dependency fix for `result`.
=> nocrypto: backport fix for parallel builds from opam-repository

packages/upstream/lwt_log.1.0.0/descr, packages/upstream/lwt_log.1.0.0/opam, packages/upstream/lwt_log.1.0.0/url, packages/xs-extra/message-switch.master/opam, packages/xs-extra/wsproxy.master/opam, packages/xs-extra/xapi-nbd.master/opam, packages/xs/nbd.4.0.0+beta1/opam
Prepare for the separation of the deprecated Lwt_log library: in the
future it will be split it into a completely separate lwt_log package,
which is currently a "proxy" package to make the transition smooth.
=> Add lwt_log package

packages/upstream/ocb-stubblr.0.1.1/files/0001-bytecode-custom-needs-cclib-as-well.patch, packages/upstream/ocb-stubblr.0.1.1/opam
See https://github.com/pqwy/ocb-stubblr/pull/11
This enables us to do `jbuilder utop ocaml/xapi` and be able to
triage issues using the internal xapi library.
=> ocb-stubblr: bytecode/custom targets need cclib as well

packages/upstream/shared-block-ring.2.4.0+1/opam
This should fix some of the travis issues
=> shared_block_ring: add missing opam dependency

packages/upstream/ppx_cstruct.3.2.1/opam
Upgrades:
- ppxlib: 0.2.0->0.3.0
- ppx_typerep_conv: v0.11.0->v0.11.1
- ppx_sexp_conv: v0.11.1->v0.11.2
- ppx_enumerate: v0.11.0->v0.11.1
- ppx_compare: v0.11.0->v0.11.1
- ppx_hash: v0.11.0->v0.11.1
- ppx_variants_conv: v0.11.0->v0.11.1
- ppx_bin_prot: v0.11.0->v0.11.1
ppx_cstruct: remove unnecessary test dependency (should fix xcp-idl travis tests)
=> xs-opam: auto update

packages/upstream-extra/merlin.3.0.5/descr, packages/upstream-extra/merlin.3.0.5/opam, packages/upstream-extra/merlin.3.0.5/url, packages/upstream-extra/ocp-build.1.99.20-beta/descr, packages/upstream-extra/ocp-build.1.99.20-beta/opam, packages/upstream-extra/ocp-build.1.99.20-beta/url, packages/upstream-extra/ocp-indent.1.6.1/descr, packages/upstream-extra/ocp-indent.1.6.1/opam, packages/upstream-extra/ocp-indent.1.6.1/url
These will not be installed by default, but will be installable with `opam` by developers
=> upstream-extra: add merlin and ocp-indent for convenience

packages/upstream-extra/diet/diet.0.1/descr, packages/upstream-extra/diet/diet.0.1/opam, packages/upstream-extra/diet/diet.0.1/url
See build failure on https://github.com/xapi-project/xcp-idl/pull/231
=> Add missing package diet: required by Travis on xcp-idl due to mirage-block-unix

README.md
We've already started using some new language features, so update the
README to point to the compiler version we are actually using.
Unfortunately there is no OCaml 4.06.1 on the docker registery, just
4.06.0: https://github.com/avsm/ocaml-docker-scripts/issues/5
=> Update README to point to OCaml 4.06.x

packages/upstream/vhd-format.0.9.2+4/opam
This dependency is added by one of the patches to the opam file, but
that does not work - we have to change the opam file itself.
=> vhd-format: add required integers dependency from patch

packages/xs-extra/xapi.master/opam
The dependencies are required because xapi vendors ocaml-pci, which
requires them.
=> xapi.opam: add dependency on ctypes for ocaml-pci

packages/upstream-extra/depext.1.0.5/descr, packages/upstream-extra/depext.1.0.5/opam, packages/upstream-extra/depext.1.0.5/url, packages/upstream-extra/depext.transition/opam
After removing depext, we now need to install opam-depext.
=> Fix Travis: install opam-depext

packages/xs-extra-dummy/xapi-clusterd-test.master/opam
So now we can install all the dependencies using opam to build
xapi-clusterd.
=> Add xapi-clusterd-test.opam

Makefile, packages/ocaml/base-bigarray.base/descr, packages/ocaml/base-bigarray.base/opam, packages/ocaml/base-bytes.base/descr, packages/ocaml/base-bytes.base/opam, packages/ocaml/base-threads.base/descr, packages/ocaml/base-threads.base/opam, packages/ocaml/base-unix.base/descr, packages/ocaml/base-unix.base/opam, packages/ocaml/ocaml-base-compiler.4.06.1/opam, tools/Dockerfile, tools/travis.sh
Using this repository as a base repository so far only worked for opam install but failed for opam depext for reasons that are not entirely clear. This series of commits tried to fix it while also making sure it still works for building RPMs from an archive of this repository.
* The "all" target is more useful now: it builds a docker container which can be used for development
* packages/ocaml/base-* was in Opam 1 format - so updated to Opam 2
* added ocam-base-compiler - this is required to make depext work although this is not obvious from the dependencies
* in tools/travis.sh, use "opam depext" again
* When building a tarball, don't cache the OCaml compiler
* Accidentally already pushed with a prior commit: a patch for Core's time function
```
Makefile …
```
=> make depext work again, various improvements

packages/upstream/cohttp-async.1.1.1/opam, packages/upstream/cohttp-lwt-unix.1.1.1/opam, packages/upstream/cohttp-lwt.1.1.1/opam, packages/upstream/cohttp.1.1.1/opam
This adds an important version bound on uri, which prevents compilation
failures with uri 2.0.0, which is the latest upstream version.
=> Sync cohttp opam files with upstream repo

packages/xs-extra/nbd-tool.master/opam, packages/xs-extra/rrd-transport.master/opam, packages/xs-extra/xapi-storage-cli.master/opam, packages/xs-extra/xapi-storage.master/opam, packages/xs-extra/xen-api-sdk.master/opam
Use the same opam files as they are in the repositories of these
packages:
* packages/xs-extra/nbd-tool.master/opam
* packages/xs-extra/rrd-transport.master/opam
* packages/xs-extra/xapi-storage-cli.master/opam
* packages/xs-extra/xapi-storage.master/opam
* packages/xs-extra/xen-api-sdk.master/opam
=> Sync opam files from component repositories

packages/xs/xapi-backtrace.0.7/opam
There were commits on xapi-backtrace that were not released yet, including some dependency cleanups.
Opening this PR to see if everything else still builds with the new xapi-backtrace.
=> xapi-backtrace: v0.6 -> v0.7

packages/upstream/dune.1.4.0/opam
Dune now supports DESTDIR, which means that it prepends it to all paths.
Our makefiles were already prepending DESTDIR so this breaks the RPM
builds.
Revert dune update until we fix the Makefiles: https://github.com/ocaml/dune/issues/1538
=> revert dune to 1.4.0: DESTDIR gets appended twice

packages/xs-extra/message-switch-async.master/opam, packages/xs-extra/message-switch-cli.master/opam, packages/xs-extra/message-switch-core.master/opam, packages/xs-extra/message-switch-lwt.master/opam, packages/xs-extra/message-switch-unix.master/opam, packages/xs-extra/message-switch.master/opam, packages/xs-extra/xapi-netdev.master/opam
This one goes with
- https://github.com/xapi-project/netdev/pull/11
- https://github.com/xapi-project/message-switch/pull/48
Please let me know if there  is a reason why we may be unable to deprecate xcp-inventory
=> Port to dune for message-switch-* and netdev

packages/xs/nbd-lwt-unix.4.0.0+beta1/opam
This is to ensure that we will compile nbd-lwt-unix with a compatible
version of the nbd library. Nbd 4.0.0 has introduced some new values
that this version of nbd-lwt-unix relies on, it does not work with nbd
3.X.
=> nbd-lwt-unix: add lower bound on nbd package to ensure compatibility

packages/xs-extra/xenctrl.master/opam
Add ocamlbuild as a dependency - which was missing.
=> xenctrl: add missing dependency

packages/upstream/dune.1.6.3/opam
This updates dune to 1.6 and it will be used on all Travis builds. However, we will need to update Makefiles and SPEC files before we use release xs-opam to be used in RPM builds. These changes are currently in preparation on `dune-1.6` branches across components.
=> Update dune to 1.6.3

packages/xs-extra/xenctrl.master/opam
This commit puts a new `xenctrl` into xs-opam, replacing the existing implementation under the same name. The repository for this is still in my personal github accout. We could move it later, or close this and do that first. 
=> Use new xenctrl.master

packages/xs/stdext.4.5.0/opam, packages/xs/xapi-stdext-base64.4.5.0/opam, packages/xs/xapi-stdext-bigbuffer.4.5.0/opam, packages/xs/xapi-stdext-date.4.5.0/opam, packages/xs/xapi-stdext-deprecated.4.5.0/opam, packages/xs/xapi-stdext-encodings.4.5.0/opam, packages/xs/xapi-stdext-monadic.4.5.0/opam, packages/xs/xapi-stdext-pervasives.4.5.0/opam, packages/xs/xapi-stdext-range.4.5.0/opam, packages/xs/xapi-stdext-std.4.5.0/opam, packages/xs/xapi-stdext-threads.4.5.0/opam, packages/xs/xapi-stdext-unix.4.5.0/opam, packages/xs/xapi-stdext-zerocheck.4.5.0/opam
Also rename all aliases to use the same version number as the underlying
code base.
=> Release stdext 4.5.0

packages/xs/xapi-stdext-unix.4.3.1/opam
Also name the package after the version it fetches, not an artificial
version that is unrelated to the source code.
=> CA-314001, CA-310525: fsync runtime lock fix, and statvfs fix

packages/xs/xapi-test-utils.1.2.0/opam
This updates the opam file of xapi-test-utils to use Dune but there is no code change.
=> xapi-test-utils: update to 1.2.0

packages/xs-extra/xapi.master/opam, tools/travis.sh
Xapi will soon gain xxhash as a new external dependency. it is not yet available in the current distribution we use for builds on Travis. Therefore:
* record the dependency in xapi's opam file
* use debian-unstable for Travis
=> Prepare for xxhash external dependency

packages/xs/qmp.0.18.0/opam
Update to qmp for added query-chardev command.
=> CA-318579 update qmp to 0.18.0 for "query-chardev"

packages/xs-extra/xapi-cli-protocol.req-627/opam, packages/xs-extra/xapi-client.req-627/opam, packages/xs-extra/xapi-consts.req-627/opam, packages/xs-extra/xapi-database.req-627/opam, packages/xs-extra/xapi-datamodel.req-627/opam, packages/xs-extra/xapi-idl.req-627/opam, packages/xs-extra/xapi-types.req-627/opam, packages/xs-extra/xapi-xenopsd-simulator.req-627/opam, packages/xs-extra/xapi-xenopsd-xc.req-627/opam, packages/xs-extra/xapi-xenopsd.req-627/opam, packages/xs-extra/xapi.req-627/opam, packages/xs-extra/xe.req-627/opam
Set up a feature branch where the following components track the HEAD
for branch REQ-627 instead of master:
* xapi-client.req-627
* xapi-consts.req-627
* xapi-database.req-627
* xapi-datamodel.req-627
* xapi-idl.req-627
* xapi-types.req-627
* xapi-xenopsd-simulator.req-627
* xapi-xenopsd-xc.req-627
* xapi-xenopsd.req-627
* xapi.req-627
* xe.req-627
=> REQ-627 set up feature branch

packages/xs-extra-dummy/xs-toolstack.master/opam
Signed-off-by: Rob Hoes <rob.hoes@citrix.com>
=> xs-toolstack: remove unused xapi-netdev dependency

packages/xs/xapi-rrd.1.6.0/opam
* 4a86fb5 CA-322008: Report out-of-bounds PDP values as NaN
* 67ea741 maintenance: whitespace and commented code deletion
* 3103ae6 maintenance: use infix operators for Int64 in rrd
* 9718e95 CA-322008: Reorganize code for incoming values by type
* c986340 CA-322008: do not treat DERIVE sources as COUNTER
* b028c29 tests: add regression test for CA-322008
=> xcp-rrd update to 1.6.0 for CA-322008

packages/xs-extra/http-svr.master/opam, packages/xs-extra/message-switch-async.master/opam, packages/xs-extra/message-switch-cli.master/opam, packages/xs-extra/message-switch-core.master/opam, packages/xs-extra/message-switch-lwt.master/opam, packages/xs-extra/message-switch-unix.master/opam, packages/xs-extra/message-switch.master/opam, packages/xs-extra/rrd-transport.master/opam, packages/xs-extra/rrd2csv.master/opam, packages/xs-extra/rrdd-plugin.master/opam, packages/xs-extra/vhd-tool.master/opam, packages/xs-extra/wsproxy.master/opam, packages/xs-extra/xapi-networkd.master/opam, packages/xs-extra/xapi-rrdd.master/opam, packages/xs-extra/xapi-squeezed.master/opam, packages/xs-extra/xapi.master/opam, packages/xs-extra/xenops.master/opam
Some files have not been pulled because of the rpc to rpclib migration, I don't know if the "ppx_deriving_rpc" are safe to remove.
=> xs-extra: update opam files from repos

packages/upstream/core.113.33.03/files/ca-297060.patch, packages/upstream/core.113.33.03/opam
Backport this to avoid spending time on every hotfix confirming that it is the same coredump we know about:
We observe core dumps in xapi-storage-script when the clock is reset
during testing. Communication with upstream suggests that this is a bug
which this commit fixes by putting in a patch.
* https://github.com/janestreet/core/issues/119
(cherry picked from commit a284382c46714e44225fe72df49debd913154b9c)
Signed-off-by: Edwin Török <edvin.torok@citrix.com>
=> CA-324944, CA-297060 patch Core for timing functions

packages/xs-extra-dummy/xs-toolstack.master/opam, packages/xs-extra/rrddump.master/opam, packages/xs-extra/varstored-guard.master/opam, packages/xs-extra/xapi-forkexecd.master/opam, packages/xs-extra/xapi-idl.master/opam, packages/xs-extra/xapi-plugin.master/opam, packages/xs-extra/xapi-squeezed.master/opam, packages/xs-extra/xapi-storage.master/opam, packages/xs-extra/xen-api-client-async.master/opam, packages/xs-extra/xen-api-client-lwt.master/opam, packages/xs-extra/xen-api-client.master/opam, tools/generate-opam-sources.sh
It also adds the url fields as necessary, reducing handywork needed to maintain the duplicated opam files.
=> Add tool to import opam files into xs-extra

README.md, tools/xs-opam-ci.env
This allows us to centrally manage the docker images, ocaml version and repo branch.
Working example: https://travis-ci.com/psafont/xcp-rrd/jobs/225775235
Existing repositories can be modified progressively to adopt the new pattern
=> tools: add env file to load xs-opam settings on travis

packages/upstream/logs-syslog.0.2.1/opam, packages/upstream/syslog-message.1.1.0/opam
These packages facilitate https://github.com/xapi-project/message-switch/issues/39.
I still need to test my changes for message switch, but I think it's pretty certain that logs-syslog will be used in any case.
The syslog library could potentially replace our custom bindings for syslog in xcp-idl to avoid repetition (lwt_log had its own implementation as well)
=> CP-32138: Add logs-syslog and dependencies

packages/xs-extra/xapi-xenopsd.master/opam
Xenopsd depends on Dump.record from fmt which is not present in fmt
0.8.6 at least.
=> Add fmt >= 0.8.8 to xapi-xenopsd

.travis.yml, packages/ocaml/ocaml-system.4.09.0/files/gen_ocaml_config.ml.in, packages/ocaml/ocaml-system.4.09.0/opam, packages/ocaml/ocaml.4.09.0/opam, tools/travis.sh, tools/xs-opam-ci.env
* Use OCaml 4.08 by default
* Add the OCaml 4.09 compiler
* Compile with OCaml 4.09 but allow it to fail
* Compiling with OCaml 4.09 currently fails because of version constraints in upstream packages
=> Use OCaml 4.08 by default, 4.09 speculatively

packages/upstream/x509.0.8.1+1/files/0001-signature-algorithm.patch, packages/upstream/x509.0.8.1+1/opam
This is needed to enforce SHA256 as the hash signature algorithm as the current released version does not expose the signature algorithm of a certificate in any way.
There is a will to add a function to disallow signature algorithms in x509, so we might be able to use that when the time comes, see https://github.com/mirleft/ocaml-x509/issues/123
=> REQ-453: add function to x509 lib to retrieve signature algorithm

packages/upstream-extra/b0.0.0.0/opam, packages/upstream-extra/odig.0.0.4/opam, packages/upstream-extra/odoc.1.4.2/opam, packages/upstream-extra/tyxml.4.3.0/opam
This allows the generation of html documentation for all the ocaml packages used in the toolstack, still need to think how to store/show/host the html :)
=> CP-29837: use odig to build docs for all packages

packages/upstream/x509.0.9.0/opam
This introduces breaking changes and needs an updated xen-api: https://github.com/xapi-project/xen-api/pull/4032
=> CP-32663: Update x509 to 0.9.0

tools/Dockerfile
The --chown option is no longer recognised.
=> Don't use COPY --chown in Dockerfile

packages/upstream-extra/fix.20200131/opam, packages/upstream-extra/ocamlformat.0.14.1/opam, packages/upstream-extra/uucp.13.0.0/opam, packages/upstream-extra/uuseg.13.0.0/opam
These changes don't need a new xs-opam release as none of these packages is used for building the toolstack.
I'm adding this so we can have a single version of ocamlformat as reference for all devs, see https://github.com/xapi-project/xcp-idl/pull/310#discussion_r415610237
=> upstream-extras: add ocamlformat

packages/xs-extra/safe-resources.master/opam, packages/xs-extra/stunnel.master/opam, packages/xs-extra/xapi-compression.master/opam, tools/generate-opam-sources.sh
This doesn't need a new xs-opam release for the internal builds.
=> CA-337546: add safe-resources

packages/upstream-extra/depext.transition/opam
In 5769c37 we removed depext.transition, because
it claims to be redundant. Unfortunately that
broke travis, so we reintroduce it.
=> Reintroduce depext.transition

packages/upstream/conf-libev.4-11/files/build.sh, packages/upstream/conf-libev.4-11/files/discover.ml, packages/upstream/conf-libev.4-11/opam, packages/xs-extra-dummy/xs-toolstack.master/opam
Lwt by default chooses a `select` based backend which is limited to 1024
FDs.
There is also a virtual poll implementation that one could hook up to a
`poll()` called via C stubs.
However if `libev` is available then it can use an `epoll` based engine,
which doesn't require any manual C bindings.
Although varstored-guard is the package that needs this, it is
beneficial for other Lwt-based daemons too, so I add the dependency on
xs-toolstack here.
See https://github.com/xapi-project/varstored-guard/pull/7#issuecomment-648295433
=> CA-341597: add conf-libev

tools/xs-opam-ci.env
this was breaking travis builds in toolstack components
=> CI: use valid names whe nexporting env vars

.github/workflows/main.yml
Github changed how the environment variables from the matrix can be picked up, this corrects it.
fail-fast is disabled to be able to see all steps that fail and continue-on-error is enabled for the cases that are expected to fail. This masks the errors but not masking them makes github send notifications and emails reporting failures. There doesn't seem to be a fix yet for this behaviour.
The recursive job is aborted in travis due to timeout, with github this doesn't seem to be the case, it runs for a _long_ time. I'd consider fixing it or disabling it altogether.
=> CI: ensure env vars are picked correctly on github actions and PRs trigger builds

tools/Dockerfile, tools/travis.sh, tools/xs-opam-ci.env
We fall back to debian-10 to avoid a problem with the current
debian-unstable images.
=> Travis: use debian-10-ocaml-4.08

tools/Dockerfile, tools/travis.sh, tools/xs-opam-ci.env
This got broken recently, same as master branch.
It also adds environment variables that support github actions for other toolstack repos.
The github actions workflow cannot be added to lcm branches, a new workflow for stockholm needs to be added to the master branch,
=> ci: change container that travis runs for stockholm branch

.github/workflows/main.yml, .github/workflows/stockholm-lcm.yml
It's on a separate workflow file to make it easier to change the main workflow without affecting the lcm tests.
=> ci: enable github action for stockholm branch

packages/xs/xenctrl.dummy/opam
This should fix the travis failures for stockholm
=> maintenance: xenctrl.dummy depends on xen libraries

.github/workflows/lcm.yml
To trigger the building and testing on a particular commit the workflow file must be on its predecessor. This applies for prs, commits and tags.
Unfortunately scheduled runs for this branch have to be triggered by a workflow on the main branch this means we must manage two workflows for lcm, one here, one on the main branch.
I'll repurpose the existing lcm workflow in `master` to schedule runs for this branch.
=> ci: add github workflow for lcm

.github/workflows/stockholm-lcm.yml
Unfortunately scheduled jobs only trigger for master branch. The lcm branch can be hardcoded onto the checkout step, so it's still possible to test the branch.
I've removed the other triggers for the workflows since these will never happen.
=> ci: schedule jobs for stockholm lcm branch

.github/workflows/main.yml, packages/xs-extra/forkexec.master/opam, packages/xs-extra/http-svr.master/opam, packages/xs-extra/rrd2csv.master/opam, packages/xs-extra/stunnel.master/opam, packages/xs-extra/xapi-forkexecd.master/opam, packages/xs-extra/xapi-idl.master/opam, packages/xs-extra/xapi-networkd.master/opam, packages/xs-extra/xapi-squeezed.master/opam, packages/xs-extra/xapi-tapctl.master/opam, packages/xs-extra/xapi-xenopsd-xc.master/opam, packages/xs-extra/xapi.master/opam, packages/xs-extra/xe.master/opam, packages/xs/xapi-test-utils.1.4.0/opam
This fixes the xe builds and prepares the repository for the removal of stdext-monadic, only stdext packages depend on it right now.
Also relaxes the filters on the github workflows so changes can be tested in forks without PRs.
=> Synchronize metadata with the latest one in the repos

Makefile, tools/licenses.sh
Add Makefile target "licenses" to report the licenses of all toolstack
packages.
=> Add licenses target to report them

packages/xs-extra-dummy/xs-toolstack.master/opam, packages/xs/polly.0.2.0/opam
Polly is split out of xenopsd to make it available outside.
=> Add xs/polly.0.2.0

packages/xs/pci.v1.0.3/opam
Bump ocaml-pci to contain the following fix: 
- CA-266936: Move pci lookups to string_opt to prevent some segfaults
=> maintenance: bump ocaml-pci

packages/upstream/cstruct-sexp.5.1.1/opam
This brings it in line with the rest of cstruct packages
=> fix: update cstruct-sexp to 5.1.1

.github/workflows/main.yml
The cache was out of date and the workflow tried to download versions of
package that were removed.
=> ci: fix failure to download apt packages

packages/upstream-extra/ocaml-lsp-server.1.1.0/opam, packages/upstream-extra/ppx_yojson_conv_lib.v0.14.0/opam
This allows to easily use lsp in toolstack opam switches when using
editors that support it. (vscode; vim and emacs with plugins)
To use lsp, simply install the server to the xs-opam-based opam switch with `opam install ocaml-lsp-server` and configure the editor to use the binary ocamllsp binary.
For a dev version of neovim install https://github.com/neovim/nvim-lspconfig, and configure the diagnostics and keybindings like in [here](https://gitlab.com/unduthegun/dotfiles/-/blob/master/nvim/.config/nvim/lua/lsp.lua)
for vs code, install the [ocaml platform](https://marketplace.visualstudio.com/items?itemName=ocamllabs.ocaml-platform) and select the xs-opam-based switch
Other editors and plugins like coc.nvim have their own configuration steps.
=> upstream-extras: add ocaml-lsp-server package

tools/xs-opam-ci.env
ocaml-ci-scripts got changed to construct the image name from DISTRO and
OCAML_VERSION, previously it only used DISTRO.
see the change in https://github.com/ocaml/ocaml-ci-scripts/commit/071d65113021b6e48a6749907a54a685397d01f1#diff-d729a609ae42944ba5fe7f089dee3bcd844bbae8ad24e01b99bc939573e4d95f
=> tools: fix travis CI for toolstack repositories

packages/upstream/conf-libnl3.1/opam, packages/upstream/conf-xen.1/files/test.c, packages/upstream/conf-xen.1/opam
These packages ensure presence of the libnl and xen headers and free
downstream packages from having to define the correct packages for all
distributions in the depexts.
This is needed for https://github.com/xapi-project/ocaml-netlink/pull/10 and can simplify the depexts for xenopsd. (I think the conf-ssl also allows for removal of openssl and libssl depexts)
=> upstream: add conf-libnl3 and conf-xen

.github/workflows/main.yml, tools/opam-single-version-check.bash
This avoid situations like the last merge which broke building the rpm package for xs-opam.
=> ci: detect if there are packages with multiple versions

packages/upstream/conf-pam.1/files/main.c, packages/upstream/conf-pam.1/opam, packages/upstream/conf-python-2-7.1.1/files/test.py, packages/upstream/conf-python-2-7.1.1/opam, packages/xs-extra/stunnel.master/opam, packages/xs-extra/vhd-tool.master/opam, packages/xs-extra/xapi-storage.master/opam, packages/xs-extra/xapi-xenopsd-xc.master/opam, packages/xs-extra/xapi.master/opam, packages/xs-extra/xenctrl.master/opam, packages/xs/netlink.0.3.4/opam
The conf-* packages encapsulate depexts. This is convenient for us because header and binary dependencies are tough to define for all distributions and are package-specific.
Having a single dependency (like `conf-xen`) makes the dependencies easier to maintain. Right now we have depexts underspecified. Hopefully with this kind of change more dependencies can be added.
=> maintenance: replace depexts with conf- packages

packages/xs-extra/http-svr.master/opam, packages/xs-extra/xapi-libs-transitional.master/opam, packages/xs/xapi-stdext-date.4.15.0/opam, packages/xs/xapi-stdext-encodings.4.15.0/opam, packages/xs/xapi-stdext-pervasives.4.15.0/opam, packages/xs/xapi-stdext-std.4.15.0/opam, packages/xs/xapi-stdext-threads.4.15.0/opam, packages/xs/xapi-stdext-unix.4.15.0/opam, packages/xs/xapi-stdext-zerocheck.4.15.0/opam
*  unixext: remove Fdset module and stubs
*  CP-34643: Deprecated non-idiomatic pervasivesext functions
*  maintenance: reformat pervasivesext with ocamlformat
*  CP-34643: add tests for xstringext
*  xapi-stdext-std: Do not duplicate functions from Stdlib
*  maintenance: format xstringext files with ocamlformat
*  XSI-894 handle iso8601's with no timezone
=> maintenance: bump stdext

tools/xs-opam-ci.env
Backport of https://github.com/xapi-project/xs-opam/pull/522, so that travis ci can pull the ocaml 4.08 container on stockholm
=> tools: change distro variable for travis CI

packages/xs/stdext.4.11.2/opam, packages/xs/xapi-stdext-date.4.11.2/opam, packages/xs/xapi-stdext-deprecated.4.11.2/opam, packages/xs/xapi-stdext-encodings.4.11.2/opam, packages/xs/xapi-stdext-monadic.4.11.2/opam, packages/xs/xapi-stdext-pervasives.4.11.2/opam, packages/xs/xapi-stdext-range.4.11.2/opam, packages/xs/xapi-stdext-std.4.11.2/opam, packages/xs/xapi-stdext-threads.4.11.2/opam, packages/xs/xapi-stdext-unix.4.11.2/opam, packages/xs/xapi-stdext-zerocheck.4.11.2/opam
Add changes in https://github.com/xapi-project/stdext/pull/60 to xs-opam
-  CA-342171 allow clients to create an iso8601 from localtime
-  maintenance: move date tests to make backport easier
-  XSI-894 handle iso8601's with no timezone
-  XSI-894 date.iso8601.to_float should assume UTC
-  date: allow timezones other than UTC for printing
-  ci: use Stockholm's xs-opam env
=> Backport! bump stdext to v4.11.2

Makefile
`opam admin cache` exits with code 0 even when it fails to download files. This results in failures in Jenkins.
Detect errors earlier by refusing to create the tarball if there were errors from `opam admin`.
=> detect failed downloads in `opam admin cache`

packages/upstream/mirage-crypto-pk.0.8.10/opam, packages/upstream/mirage-crypto-rng.0.8.10/opam, packages/upstream/mirage-crypto.0.8.10/opam
Previous versions checked an invalid property of RSA key parameters.
Relevant commit in the packages: https://github.com/mirage/mirage-crypto/commit/46e6217ac33525f5b019f0f1fc229241f9b03328
=> CA-350872: update mirage-crypto packages

packages/upstream-extra/dot-merlin-reader.3.4.2/opam, packages/upstream-extra/merlin.3.4.2/opam, packages/upstream-extra/ocaml-lsp-server.1.4.0/opam, packages/xs-extra-dummy/upstream-extra-dummy.master/opam, packages/xs-extra-dummy/xapi-clusterd.master/opam
This prepares both for the newer versions of dune which do _not_ generate .merlin files.
The lsp server comes with some goodies:
- Support cancellation notifications when possible.
- Implement signature help request for functions
- Server LSP requests & notifications concurrently. Requests that require merlin are still serialized. 
- Code action to insert inferred module interface
- Filter keywords by context
- Add keyword completion
- Add go to declaration functionality to jump to a value's specification in a .mli file
=> upstream-extra: update merlin and ocaml-lsp-server packages

packages/xs/ezxenstore.0.4.1/opam
Now Stockholm's ezxenstore version matches master's, since there have been no other changes to ezxenstore since releasing Stockholm
=> backport! (stockholm) kdump

Makefile, packages/upstream/oasis.0.4.11/opam, packages/upstream/ocamlify.0.0.1/opam, packages/upstream/ocamlmod.0.0.9/opam, packages/xs/ezxenstore.0.4.1/opam
This PR is intended to contain kdump exclusively changes (these changes are in release/stockholm/lcm already: https://github.com/xapi-project/xs-opam/pull/549). It is intended that the branch 6.35.1-lcm will be tagged as 6.35.1.1, giving us:
6.35.1 (base) < 6.35.1.1 (kdump only) < 6.35.6 (kdump + other stockholm fixes)
=> UPD-738 port kdump on top of 6.35.1

packages/xs/xapi-stdext-date.4.17.0/opam, packages/xs/xapi-stdext-encodings.4.17.0/opam, packages/xs/xapi-stdext-pervasives.4.17.0/opam, packages/xs/xapi-stdext-std.4.17.0/opam, packages/xs/xapi-stdext-threads.4.17.0/opam, packages/xs/xapi-stdext-unix.4.17.0/opam, packages/xs/xapi-stdext-zerocheck.4.17.0/opam
This version deprecates the functions in `Listext` included from `Stdlib.List`.
I expect warnings propping up for modules in xen-api and xapi-libs-transitional, they may block the build.
They don't block the build, but there are a lot of warnings for xen-api :)
=> xs: update xapi-stdext packages to v4.17.0

packages/xs-extra/xapi-idl.master/opam
It's used for building the binary in misc
Mirrors https://github.com/xapi-project/xcp-idl/commit/04a466eed486d5822d299da280d91f8df0d55e9e
Fixes the build issue seen in https://github.com/xapi-project/xcp-networkd/pull/191
=> xs-extra: add lwt to xapi-idl's dependencies

packages/upstream/conduit-async.2.2.2-1/files/0001-backport-Add-openssl_overrides-to-conduit-context.patch, packages/upstream/conduit-async.2.2.2-1/opam, packages/upstream/conduit-lwt-unix.2.2.2-1/files/0001-backport-Add-openssl_overrides-to-conduit-context.patch, packages/upstream/conduit-lwt-unix.2.2.2-1/opam, packages/upstream/conduit-lwt.2.2.2-1/files/0001-backport-Add-openssl_overrides-to-conduit-context.patch, packages/upstream/conduit-lwt.2.2.2-1/opam, packages/upstream/conduit.2.2.2-1/files/0001-backport-Add-openssl_overrides-to-conduit-context.patch, packages/upstream/conduit.2.2.2-1/opam
- make conduit version (2.2.2) consistent across conduit packages
- apply patch: https://github.com/mirage/ocaml-conduit/commit/4efe7a57897278e8ce338ec51e09ee6c0d820fa8
Motivation for the patch is so that we can connect to a particular hostname/IP, but specify something else to verify against (SNI)
=> CP-36097 ocaml-conduit patch

packages/upstream/lwt.5.4.1/opam, packages/upstream/ppxlib.0.22.1/opam, packages/xs/pci.v1.0.4/opam, packages/xs/xapi-stdext-date.4.18.0/opam, packages/xs/xapi-stdext-encodings.4.18.0/opam, packages/xs/xapi-stdext-pervasives.4.18.0/opam, packages/xs/xapi-stdext-std.4.18.0/opam, packages/xs/xapi-stdext-threads.4.18.0/opam, packages/xs/xapi-stdext-unix.4.18.0/opam, packages/xs/xapi-stdext-zerocheck.4.18.0/opam
The ocaml-pci update allows to update ctypes to 0.18, which I'd rather wait along other, more substantial changes.
The ppxlib update fixes the location reported on errors
The LWT library fixes handling of `ECONNABORTED` for `Lwt_io.establish_server*`
the stdext updates are for listext which drops the List functions.
=> CP-34942: Update pci and xapi-stdext packages, along with some minor updatos for upstream libraries

packages/upstream/tyre.0.5/opam, packages/xs-extra/xapi-xenopsd.master/opam
Support both parsing and unparsing.
Can be used as replacement for scanf/printf to perform validation.
=> CP-37034: add tyre: library for typed regular expressions

packages/xs-extra/xapi-xenopsd-simulator.0.150.5/opam, packages/xs-extra/xapi-xenopsd-xc.0.150.5/opam, packages/xs-extra/xapi-xenopsd.0.150.5/opam
This fixes the scheduled run failure: https://github.com/xapi-project/xs-opam/runs/3052779434?check_suite_focus=true#step:3:1356
=> maintenance: use the newly-minted xenopsd stockholm branch

repo
This should minimize disruptions cause by server downtime, which is
happening quite often with inria's gitlab instance.
@mseri do you know of any downsides by doing this? I'm not worried about users not being able to configure their mirrors in this case. (https://github.com/ocaml/opam/issues/4411)
=> Use the official cache as a mirror

packages/upstream/conf-pkg-config.2/opam, packages/xs/pci.v1.0.4/opam, packages/xs/xapi-inventory.1.2.2/opam
opam 2.1.0 uses depexts for package resolution so with broken depexts
packages cannot be installed anymore
=> maintenance: fix build in opam 2.1.0

tools/travis.sh
ocaml/opam2 do not get updated anymore and have been replaced by
ocaml/opam. This fixes lcm ci.
=> ci: use updated container images

packages/xs-extra/message-switch-async.1.23.1/opam, packages/xs-extra/message-switch-cli.1.23.1/opam, packages/xs-extra/message-switch-core.1.23.1/opam, packages/xs-extra/message-switch-lwt.1.23.1/opam, packages/xs-extra/message-switch-unix.1.23.1/opam, packages/xs-extra/message-switch.1.23.1/opam, packages/xs-extra/xapi-cli-protocol.1.249.10/opam, packages/xs-extra/xapi-client.1.249.10/opam, packages/xs-extra/xapi-consts.1.249.10/opam, packages/xs-extra/xapi-database.249.10/opam, packages/xs-extra/xapi-datamodel.249.10/opam, packages/xs-extra/xapi-idl.1.96.1/opam, packages/xs-extra/xapi-types.1.249.10/opam, packages/xs-extra/xapi.1.249.10/opam, packages/xs-extra/xe.1.249.10/opam
This affects message-switch, xapi-idl and xapi, other repositories were
already branched or are still not branched.
=> fix: follow Stockholm branches after Yangtze split

packages/upstream/conf-libev.4-11/files/build.sh, packages/upstream/conf-libev.4-11/files/discover.ml, packages/upstream/conf-libev.4-11/opam, packages/xs-extra-dummy/xs-toolstack.master/opam, packages/xs-extra/varstored-guard.0.6/opam
Backports for
- CA-341597: add conf-libev, Raise the open fd limit in varstored v0.6.1
- CA-358583: Fix PROXY metadata to multiple HTTPS requests on a connection in in xen-api-libs-transitional v2.25.3 (already included in the current archive)
- Fix handling of web-dir parameter in xen-api v1.249.15 (already included in the current archive)
=> Backport fixes to yangtze

README.md
Point to GitHub Actions instead of Travis CI.
See https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge
See https://github.com/edwintorok/xs-opam/tree/badge on how this looks.
=> CI: update status badge

packages/xs-extra/http-svr.master/opam, packages/xs-extra/varstored-guard.master/opam, packages/xs-extra/vhd-tool.master/opam, packages/xs-extra/wsproxy.master/opam, packages/xs-extra/xapi-nbd.master/opam, packages/xs-extra/xapi-networkd.master/opam, packages/xs-extra/xapi-storage-cli.master/opam, packages/xs-extra/xapi-xenopsd-xc.master/opam, packages/xs-extra/xen-api-client-async.master/opam, packages/xs-extra/xen-api-client-lwt.master/opam, packages/xs-extra/xen-api-client.master/opam, tools/generate-opam-sources.sh
The only repositories that are tracked by tools/generate-opam-sources.sh and are not hosted in xen-api are
- xapi-plugin: https://github.com/xapi-project/ocaml-xapi-plugin/
- xenctrl: https://github.com/xapi-project/xenctrl
=> specsavers: move remaining independent daemons to xen-api

repo
This makes it possible to build the packages offline
=> repo: use local folder as well for cache

packages/upstream/stdlib-shims.0.3.0/opam, packages/upstream/uchar.0.0.2/opam
=> upstream: Replace 'typeof OCaml system' with a recognized SPDX

packages/xs-extra/xapi-xenopsd-xc.master/opam, packages/xs-extra/xentoollog.master/opam
This package is not to be installed in the product and is only used to
ease local development.
Depends on https://github.com/xapi-project/xenctrl/pull/4 being merged
=> CP-38617: expose xentoollog as a package and use it

packages/upstream-extra/opam-depext.1.2.1/opam, packages/xs-extra/uuid.master/opam
This allows to install depext on opam 2.1.x, which is needed for newer version of ocaml's github CI tooling.
This does not affect the tarball release
=> upstream-extra: update depext to latest version

packages/xs-extra/xapi-networkd.0.56/opam
Now that xapi-networkd 0.56.1 has been released stop using a tag and use instead the
lcm branch, like other repos do.
=> Update repos to point to lcm branches to keep up with yangtze's hotfixes

packages/upstream/conduit-async.2.2.2-1/files/0001-backport-Add-openssl_overrides-to-conduit-context.patch, packages/upstream/conduit-async.2.2.2-1/opam, packages/upstream/conduit-lwt-unix.2.2.2-1/files/0001-backport-Add-openssl_overrides-to-conduit-context.patch, packages/upstream/conduit-lwt-unix.2.2.2-1/opam, packages/upstream/conduit-lwt.2.2.2-1/files/0001-backport-Add-openssl_overrides-to-conduit-context.patch, packages/upstream/conduit-lwt.2.2.2-1/opam, packages/upstream/conduit.2.2.2-1/files/0001-backport-Add-openssl_overrides-to-conduit-context.patch, packages/upstream/conduit.2.2.2-1/opam
Backport patches in the context of Certificate Checking to the Yangtze release of xs-opam. The commits were cherry-picked and apply cleanly.
=> Backport Conduit patches to Yangtze

packages/xs-extra/xapi-cli-protocol.master/opam, packages/xs-extra/xapi-client.master/opam, packages/xs-extra/xapi-consts.master/opam, packages/xs-extra/xapi-database.master/opam, packages/xs-extra/xapi-datamodel.master/opam, packages/xs-extra/xapi-types.master/opam, packages/xs-extra/xapi.master/opam, packages/xs-extra/xe.master/opam, packages/xs-extra/xen-api-client-async.master/opam, packages/xs-extra/xen-api-client-lwt.master/opam, packages/xs-extra/xen-api-client.master/opam
This is due to https://github.com/xapi-project/xen-api/pull/4779
=> xs-extra: xen-api packages don't need to set XAPI_VERSION anymore

packages/xs-extra/rrddump.master/opam, packages/xs-extra/xapi-compression.master/opam, packages/xs-extra/xapi-consts.master/opam, packages/xs-extra/xapi-idl.master/opam, packages/xs-extra/xapi-squeezed.master/opam, packages/xs-extra/xapi.master/opam
These metadata changes depend on a dune metadata fix in https://github.com/xapi-project/xen-api/pull/4833
=> xs-extra: add missing dependencies

packages/xs/xapi-rrd.1.9.1/opam
There was a piece of code with quadratic cost that could dominate the runtime in xcp-rrdd in busy hosts
=> CA-371780: update xapi-rrd to 1.9.1

.github/workflows/draft-release.yml, .github/workflows/main.yml, .github/workflows/yangtze-lcm.yml
In particular the "official" actions to set up releases were abandoned, so the gh CLI is used instead
Signed-off-by: Pau Ruiz Safont <pau.ruizsafont@cloud.com>
=> ci: avoid deprecated actions in github

packages/xs/xenctrl.dummy/opam
Xen has dropped some packages such as xenlight already.
Draft, until I do a full chainbuild
=> xenctrl.dummy: do not rsync Xen packages we do not use

.github/duplicates-upstream-extra.txt, .github/duplicates-xs-toolstack.txt, .github/unused-upstream.txt, .github/workflows/main.yml, packages/ocaml/ocaml-base-compiler.4.14.1/files/ocaml-base-compiler.install, packages/ocaml/ocaml-base-compiler.4.14.1/opam, packages/ocaml/ocaml-system.4.14.1/files/gen_ocaml_config.ml.in, packages/ocaml/ocaml-system.4.14.1/opam, packages/ocaml/ocaml.4.14.1/opam, packages/upstream-extra/chrome-trace.3.7.0/opam, packages/upstream-extra/dot-merlin-reader.4.6/opam, packages/upstream-extra/dune-rpc.3.6.2/opam, packages/upstream-extra/dyn.3.6.2/opam, packages/upstream-extra/fiber.3.6.2/opam, packages/upstream-extra/merlin-lib.4.6-414/opam, packages/upstream-extra/merlin.4.6-414/opam, packages/upstream-extra/ocaml-lsp-server.1.15.1-4.14/opam, packages/upstream-extra/ocamlc-loc.3.6.2/opam, packages/upstream-extra/ocamlformat-rpc-lib.0.22.4/opam, packages/upstream-extra/octavius.1.2.2/opam, packages/upstream-extra/omd.1.3.2/opam, packages/upstream-extra/ordering.3.6.2/opam, packages/upstream-extra/stdune.3.6.2/opam, packages/upstream-extra/xdg.3.6.2/opam, packages/upstream/either.1.0.0/opam, packages/upstream/ocamlformat.0.22.4/opam, packages/upstream/odoc-parser.1.0.0/opam
Update packages to be compatible with ocaml 4.14.
Some packages around ocamlformat need to have 2 versions to be able to work in both versions of the compilers, this affects the artifacts that generated from this version.
Because the ocamlformat version has been changed once we move to ocaml 4.14 the formatting of xapi will need to change accordingly
I would rather wait until 4.14.1 is available before merging this, it is probably a good idea to merge the upstream changes before this one as well.
=> ocaml: add 4.14

packages/xs-extra/vhd-format-lwt.master/opam, packages/xs-extra/vhd-format.master/opam
Now it's vendored in the xapi repository, this should fix xs-opam's CI
=> vhd-format: move from upstream to xs-extra

packages/ocaml/ocaml-base-compiler.4.08.1/files/alt-signal-stack.patch, packages/ocaml/ocaml-base-compiler.4.08.1/opam
github did the old switcheroo and changes the context of a patch file. This is probably because github doesn't use full commit indeces by default in these file and it needed longer hashes to differenciate between commits.
This change is needed to pass the CI, it doesn't affect the tarball that's being packaged for releases
=> ocaml: harden against patchset checksum changing

packages/upstream/batteries.3.6.0/opam, packages/upstream/ppx_deriving_rpc.9.0.0/opam, packages/upstream/rpclib-async.9.0.0/opam, packages/upstream/rpclib-lwt.9.0.0/opam, packages/upstream/rpclib.9.0.0/opam, packages/xs-extra/forkexec.master/opam, packages/xs-extra/message-switch-async.master/opam, packages/xs-extra/message-switch-cli.master/opam, packages/xs-extra/message-switch-core.master/opam, packages/xs-extra/message-switch-lwt.master/opam, packages/xs-extra/message-switch-unix.master/opam, packages/xs-extra/message-switch.master/opam, packages/xs-extra/rrdd-plugin.master/opam, packages/xs-extra/rrdd-plugins.master/opam, packages/xs-extra/xapi-forkexecd.master/opam, packages/xs-extra/xapi-idl.master/opam, packages/xs-extra/xapi-rrdd-plugin.master/opam, packages/xs-extra/xapi-squeezed.master/opam, packages/xs-extra/xapi-storage-script.master/opam, packages/xs-extra/xapi-storage.master/opam, packages/xs/polly.0.3.0/opam, packages/xs/xapi-backtrace.0.7/opam, packages/xs/xapi-test-utils.1.4.0/opam
Fix `opam source --dev rpclib -vv` to use the github https URL instead of the git:// protocol which was discontinued by github.
Co-authored-by: @edwintorok
=> packages/upstream/rpclib*/opam: dev-repo must use github https

packages/upstream/uri-sexp.4.3.0/files/ipv6.patch, packages/upstream/uri-sexp.4.3.0/opam, packages/upstream/uri.4.3.0/files/ipv6.patch, packages/upstream/uri.4.3.0/opam, packages/xs-extra/xapi-open-uri.master/opam, packages/xs-extra/xapi-storage.master/opam
I've manually tested it works as expected using a utop session:
```
- : string = ""
- : string option = Some "::1"
```
I've also tweaked some xs-extra packages so they can be installed and compiled more reliably
=> upstream: patch uri packages to parse ipv6 addresses correctly

.github/workflows/main.yml, tools/find-unused-packages.sh, tools/no-duplicates-check.bash
This copies what is being used for the yangtze builds, which take about 11 to 15 minutes compared to 21 to 27 when running with a cold cache and around 9 to 11 minutes with a warm cache
=> ci: update setup-ocaml to v2

.github/workflows/main.yml
With v2 the runners consistently get out of disk space and make the ci fail
This reverts commit 6ffdaf74d2de345157f0366771f0fe755995defc.
The out-of-disk issue doesn't happen for yangtze, probably because of the amount of libraries that need to be compiled. I'll try again with v2 once the work for dropping async and core libraries is done
=> Revert "ci: update setup-ocaml to v2"

README.md
Refer to XenServer (again) instead of Citrix Hypervisor.
=> Update README, s/Citrix/XenServer/g

.github/workflows/main.yml
On the last week CI runs have started to fail consistently because they run out of space. The default runner images have way too many files that are useless for building ocaml.
Start with the removal of android tools, we'll see if it's enough, I don't want to remove all tools because it can also take a couple of minutes to do so.
=> github: update image and free space

packages/xs-extra/xapi-tracing.master/opam
=> xs-extra: add newly added dependency for xapi-tracing

packages/upstream/conf-python-3.9.0.0/opam
Forcing 3.9 broke centos 7 as only 3.6 is available
=> upstream: use python3 in all centos distributions

packages/upstream/vhd-format-lwt.0.12.1/files/0001-XSI-1457-Limit-number-of-sectors-to-coalesce.patch, packages/upstream/vhd-format-lwt.0.12.1/opam, packages/upstream/vhd-format.0.12.1/files/0001-XSI-1457-Limit-number-of-sectors-to-coalesce.patch, packages/upstream/vhd-format.0.12.1/opam
We are patching an upstream project by adding a patch to the opam file. The original is here:
https://github.com/xapi-project/xen-api/commit/db4d465f16745892b4d4ff37d44f8dbd72182314
=> Add patch for XSI-1457 to ocaml-vhd

.github/workflows/main.yml, tools/xs-opam-ci.env
The current removal of files in the root filesystem is not enough anymore. Since it takes more than half a minute to remove these files and doesn't provide us with enough benefit, instead use Edwin's change of disks from
https://github.com/xapi-project/xen-api/commit/534eb8dc1d0c37e28a67da4fc53e4cd60e11ab62
This alone has avoided xapi's workflow from running out of disk space, so hopefully it also works here.
Example of run failing due to lack of disk space: https://github.com/xapi-project/xs-opam/actions/runs/9459249982/job/26056017881
=> ci: add Edwin's disk switch

packages/xs-extra/xapi-stdext-unix.master/opam
Depends on https://github.com/xapi-project/xen-api/pull/5721/
Added `unix-errno` and `astring` as dependencies for the standalone implementation - these are already packaged.
=> IH-583: Add new dependencies of the standalone systemd implementation

packages/upstream/jst-config.v0.15.1/files/a5cddd0e657b9fc3f6775da8ebdaa6d25446b649.patch, packages/upstream/jst-config.v0.15.1/opam
Backport https://github.com/janestreet/jst-config/commit/a5cddd0e657b9fc3f6775da8ebdaa6d25446b649.patch
=> jst-config: fix build on Fedora40

tools/license-check.sh
https://spdx.github.io/spdx-spec/v2.3/SPDX-license-expressions/#d2-case-sensitivity says:
> License expression operators (AND, OR and WITH) should be matched in a case-sensitive manner.
> License identifiers (including license exception identifiers) used in SPDX documents or source code files should be matched in a case-insensitive manner
=> [maintenance]: SPDX license identifiers are not case sensitive

packages/xs-extra/ezxenstore.master/opam, packages/xs-extra/xapi-rrdd.master/opam
Equivalent commit in XAPI is in this PR:
https://github.com/xapi-project/xen-api/pull/5982/commits/0a8fc6e64b0c59a8cb2d5ddf6d9fba68e9d0e7b3
This is fallout from the epoll merge which introduced this additional dependency, and although it didn't cause a failure in the XAPI CI, it did one here.
=> update ezxenstore.opam dependencies [epoll]

packages/upstream/jst-config.v0.15.1/opam
Run opam admin update-extrafiles to add the missing metadata for the jst-config patch, otherwise opam 2.3.0 refuses to load the file.
=> maintenance: prepare for opam 2.3.0

packages/xs-extra/xapi-storage-script.master/opam
This doesn't remove any of the async dependencies, yet. This is so we
can quickly back off the changes. Once the new daemon has been published
to customers, all the async dependencies can be dropped.
Also removes the dependency on python2, which was removed some months ago
=> xs-extra: add lwt dependencies from xapi-storage-script

packages/xapi-test-utils/xapi-test-utils.1.4.0/opam
This dependency is missed by the current cropping of dependencies.
=> xapi-test-utils: add crowbar to the dependencies

packages/upstream/vhd-format-lwt.0.12.1/opam, packages/upstream/vhd-format.0.12.1/opam
Opam 2.3.0 does not copy the patch files into the repository otherwise, and the packages cannot be built.
This was done using `opam admin update-extrafiles`
This patch only affects dev environments, as the build system does not use opam 2.3.0
=> upstream: add hash for patch files

packages/bigstring-unix/bigstring-unix.0.3/opam, packages/bigstring/bigstring.0.3/opam, packages/faraday/faraday.0.8.2/opam, packages/gluten/gluten.0.5.2/opam, packages/h2/h2.0.13.0/opam, packages/hpack/hpack.0.13.0/opam, packages/httpun-types/httpun-types.0.2.0/opam, packages/httpun/httpun.0.2.0/opam, packages/xs-toolstack/xs-toolstack.master/opam
These HTTP/1 and HTTP/2 libraries have shown promising results in experiments. Add them to facilitate the next steps.
=> Add httpun and h2 (with dependencies)

.github/workflows/yangtze-lcm.yml
In 2 days the image is being removed, making the tests fail continuously
Needs https://github.com/xapi-project/xs-opam/pull/727 merged before runs are successful
=> github: update image for yangtze's scheduled CI

packages/mirage-block-combinators/mirage-block-combinators.3.0.2/opam, packages/mirage-sleep/mirage-sleep.4.0.0/opam, packages/qcow-tool/qcow-tool.0.12.1/opam, packages/qcow/qcow.0.12.1/opam, packages/unix-type-representations/unix-type-representations.0.1.2/opam, packages/xapi/xapi.master/opam
Add qcow-tool's dependencies: qcow, mirage-sleep, mirage-block-combinators, unix-type-representations
(I was hoping I could get by with just `qcow-stream` and `qcow-types`, but we have to use the CLI tool after all)
=> packages: Add qcow-tool as xapi's dependency

packages/ocamlformat/ocamlformat.0.27.0/opam
This is done to avoid changing the formatting on xapi while still allowing compilation of all the tools in ocaml 5 for the rpms.
With the PR ocamlformat 0.26.2 is installed when using ocaml 4.14: https://github.com/xapi-project/xs-opam/actions/runs/17910307744/job/50920143220?pr=739#step:11:146
=> packages: limit ocamlformat 0.27.0 to ocaml 5

Makefile
Historically all of them have been required by some package, other than the compiler. This is not the case for base-domains and base-nnp. It's time to be explicit about them.
I've manually built the tarball, in a 4.14 and a 5.3 switch, and inspected the contents:
```
$ tar -tf  xs-opam-repo-6.93.0-2-g3c83860c.tar.gz | grep base-domains
xs-opam-repo-6.93.0-2-g3c83860c/packages/base-domains/
xs-opam-repo-6.93.0-2-g3c83860c/packages/base-domains/base-domains.base/
xs-opam-repo-6.93.0-2-g3c83860c/packages/base-domains/base-domains.base/opam
```
=> Makefile: Be explicit about retaining the base packages
